<a href="https://colab.research.google.com/github/onlyone11s/Numpy-Course/blob/main/Numpy_Example_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Example

In [25]:
import numpy as np
arr = np.array([1,2,3,8,5,2])
print(arr)
#check data type
print(type(arr))



[1 2 3 8 5 2]
<class 'numpy.ndarray'>


# ckeck number array by indexing
# Accessing elements of the array

In [27]:
print("first element :",arr[0])
print("last element :",arr[-1])
print("last element :",arr[5])
print("last element :",arr[3])
# slicing
print ("element at index 3 and 4 : ", arr[1:7:2])

first element : 1
last element : 2
last element : 2
last element : 8
element at index 3 and 4 :  [2 8 2]


# Performing operations on the array
print("Sum of all elements:", np.sum(my_array))
print("Product of all elements:", np.prod(my_array))
print("Mean of all elements:", np.mean(my_array))
print("Maximum element:", np.max(my_array))
print("Minimum element:", np.min(my_array))

In [34]:
#[1 2 3 8 5 0 2]
print("sum of all element:" ,np.sum(arr))
print("Product/multiple of all elements: ",np.prod(arr))
print("Mean of all element:",np.mean(arr))
print("Maximum element :",np.max(arr))
print("Minimum element :", np.min(arr))

sum of all element: 21
Product/multiple of all elements:  480
Mean of all element: 3.5
Maximum element : 8
Minimum element : 1


# Creating a 2D array
my_2d_array = np.array([[1, 2, 3], [4, 5, 6]])

# Printing the 2D array
print("2D NumPy Array:")
print(my_2d_array)

In [37]:
a2darr=np.array([[1,2,34],[2,8,4]])
print("2D numpy array: ")
print(a2darr)

2D numpy array: 
[[ 1  2 34]
 [ 2  8  4]]


# Accessing elements of the 2D array
print("Element at row 1, column 2:", my_2d_array[1, 2])
print("First row:", my_2d_array[0, :])
print("Second column:", my_2d_array[:, 1])

In [44]:
print("element at row 1,column 2:",a2darr[1,2])
print("First Row:",a2darr[0,:] )
print("second Column:", a2darr[:,1])


element at row 1,column 2: 4
First Row: [ 1  2 34]
second Column: [2 8]


# complex ,float , str etc
a = numpy.array([1, 3, 5, 7], complex)  


In [50]:
a=np.array([1,2,3,4],dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [56]:
a= np.array([1,2,6,8,],str)
print(a)

['1' '2' '6' '8']


In [57]:
a= np.array([1,2,6,8,],float)
print(a)

[1. 2. 6. 8.]


In [63]:
e =np.array([[[2,1,3,4],[5,7,8,3]],[[5,5,7,2],[4,6,8,3]]])
print(e)
print("shape=",np.shape(e))
print("dimensionl array=",np.ndim(e))

[[[2 1 3 4]
  [5 7 8 3]]

 [[5 5 7 2]
  [4 6 8 3]]]
shape= (2, 2, 4)
dimensionl array= 3


In [76]:
# one D array
a=np.array([2,3,5,6])
print(a)
print(np.ndim(a))
q=np.shape(a)
print(q)
#2 D array
a=np.array([[2,3,5],[1,3,4]])
print(a)
print(np.ndim(a))
q=np.shape(a)
print(q)


#3 D array
print("3 Darray")
a=np.array([[[2,3],[6,9]],[[1,3],[3,6]]])
print(a)
print(np.ndim(a))
q=np.shape(a)
print(q)


[2 3 5 6]
1
(4,)
[[2 3 5]
 [1 3 4]]
2
(2, 3)
3 Darray
[[[2 3]
  [6 9]]

 [[1 3]
  [3 6]]]
3
(2, 2, 2)


In [77]:
a=np.array([[[[2,3],[6,9]],[[1,3],[3,6]]]])
print(a)
print(np.ndim(a))
q=np.shape(a)
print(q)

[[[[2 3]
   [6 9]]

  [[1 3]
   [3 6]]]]
4
(1, 2, 2, 2)
