<a href="https://colab.research.google.com/github/onlyone11s/Numpy-Course/blob/main/Numpy_Topic_01_Numpy_Creating_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What is NumPy?
NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.
* Numpy Stand for Numerical Python.

# Numpy creating array
**one dimensional array**
In this code, we first import the NumPy library and assign it the alias np using the statement import numpy as np. This allows us to use the NumPy functions and objects using the shorthand np.

Next, we create a NumPy array a using the np.array() function. The np.array() function takes a sequence-like object (such as a list) as an argument and converts it into a NumPy array. In this case, we pass the list [2, 3, 4, 5] to create the array a.

Finally, we use the print() function to display the original array a on the console. The message "Original array:" is printed along with the value of the array a.

In [ ]:
import numpy

a =numpy.array([2,3,4,5])
print("Original array",a)

Original array [2 3 4 5]


n this code, we import the NumPy library using the import numpy as np statement. Then, we create a NumPy array a using the np.array() function and provide the elements [2, 3, 4, 5]. Finally, we use the print() function to display the original array a on the console.


In [ ]:
import numpy as np
a = np.array([2,3,4,5])
print("Original array",a)
b = np.ndim(a)
print("number of dimensional array=",b)
print()
c = np.shape(a)
print(c)
print()
d = np.size(a)
print("Size of array=",d)

Original array [2 3 4 5]
number of dimensional array= 1

(4,)

Size of array= 4


In this code, we first import the NumPy library using import numpy as np.

We then create a NumPy array a with the elements [2, 3, 4, 5] using the np.array() function.

Next, we print the original array a using the print() function and the message "Original array:".

After that, we use the np.ndim() function to determine the number of dimensions of the array a. The np.ndim() function returns an integer that represents the number of dimensions in the array. We assign this value to the variable b.

We print the number of dimensions using the print() function and the message "Number of dimensions of the array =". This statement displays the value of b, which represents the number of dimensions in the array a.

Next, we use the np.shape() function to determine the shape of the array a. The np.shape() function returns a tuple that represents the size of each dimension in the array. We assign this tuple to the variable c.

We print the shape of the array using the print() function and the message "Shape of the array:". This statement displays the value of c, which represents the shape of the array a.

Finally, we use the np.size() function to determine the size of the array a, which is the total number of elements in the array. The np.size() function returns an integer representing the size. We assign this value to the variable d.

We print the size of the array using the print() function and the message "Size of the array =". This statement displays the value of d, which represents the size (total number of elements) of the array a.

**Two dimensional Array**

In [2]:
import numpy as np

a = np.array([[[2, 3, 4, 5], ['6', 7, 8, 9]], [[1, 2, 3, 6], [4, 5, 6, 7]], [[12, 13, 14, 15]]])
print("Original array:", a)

# Check the data type of the array
print("Array data type:", a.dtype)

# Determine the number of dimensions
b = np.ndim(a)
print("Number of dimensions of the array:", b)

# Determine the shape of the array
c = np.shape(a)
print("Shape of the array:", c)

# Determine the size of the array
d = np.size(a)
print("Size of the array:", d)

Original array: [list([[2, 3, 4, 5], ['6', 7, 8, 9]]) list([[1, 2, 3, 6], [4, 5, 6, 7]])
 list([[12, 13, 14, 15]])]
Array data type: object
Number of dimensions of the array: 1
Shape of the array: (3,)
Size of the array: 3


<ipython-input-2-a9b8b3194aca>:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.array([[[2, 3, 4, 5], ['6', 7, 8, 9]], [[1, 2, 3, 6], [4, 5, 6, 7]], [[12, 13, 14, 15]]])


# Explanation
In this code, we import the NumPy library using import numpy as np.

We create a NumPy array a with multiple dimensions and various elements using the np.array() function. The array a contains three nested lists, each representing a different dimension.

We then print the original array a using the print() function and the message "Original array:".

To check the data type of the array, we use the dtype attribute of the array a and print it using the print() function and the message "Array data type:".

Next, we determine the number of dimensions of the array a using the np.ndim() function. The np.ndim() function returns an integer representing the number of dimensions in the array. We assign this value to the variable b and print it using the print() function and the message "Number of dimensions of the array:".

We determine the shape of the array a using the np.shape() function. The np.shape() function returns a tuple representing the size of each dimension in the array. We assign this tuple to the variable c and print it using the print() function and the message "Shape of the array:".

Finally, we determine the size of the array a using the np.size() function. The np.size() function returns an integer representing the total number of elements in the array. We assign this value to the variable d and print it using the print() function and the message "Size of the array:".

**Three Dimensional Array**

In [3]:
import numpy as np

a = np.array([[[[2, 3, 4, 5], [6, 7, 8, 9]], [[12, 13, 14, 15], [13, 14, 15, 16]]]])
print("Original array:", a)

# Determine the number of dimensions
b = np.ndim(a)
print("Number of dimensions of the array:", b)

# Determine the shape of the array
c = np.shape(a)
print("Shape of the array:", c)

# Determine the size of the array
d = np.size(a)
print("Size of the array:", d)

Original array: [[[[ 2  3  4  5]
   [ 6  7  8  9]]

  [[12 13 14 15]
   [13 14 15 16]]]]
Number of dimensions of the array: 4
Shape of the array: (1, 2, 2, 4)
Size of the array: 16


# Explanation

Certainly! Here's the code with comments and explanations:

python
Copy code
import numpy as np

a = np.array([[[[2, 3, 4, 5], [6, 7, 8, 9]], [[12, 13, 14, 15], [13, 14, 15, 16]]]])
print("Original array:", a)

# Determine the number of dimensions
b = np.ndim(a)
print("Number of dimensions of the array:", b)

# Determine the shape of the array
c = np.shape(a)
print("Shape of the array:", c)

# Determine the size of the array
d = np.size(a)
print("Size of the array:", d)
In this code, we import the NumPy library using import numpy as np.

We create a NumPy array a with multiple dimensions and various elements using the np.array() function. The array a contains nested lists representing different dimensions.

We then print the original array a using the print() function and the message "Original array:".

To determine the number of dimensions of the array a, we use the np.ndim() function. The np.ndim() function returns an integer representing the number of dimensions in the array. We assign this value to the variable b and print it using the print() function and the message "Number of dimensions of the array:".

To determine the shape of the array a, we use the np.shape() function. The np.shape() function returns a tuple representing the size of each dimension in the array. We assign this tuple to the variable c and print it using the print() function and the message "Shape of the array:".

To determine the size of the array a, we use the np.size() function. The np.size() function returns an integer representing the total number of elements in the array. We assign this value to the variable d and print it using the print() function and the message "Size of the array:".

In [4]:
import numpy as np

a = np.array([[[[2, 3, 4, 5]]]])
print("Original array:", a)

# Determine the number of dimensions
b = np.ndim(a)
print("Number of dimensions of the array:", b)

# Determine the shape of the array
c = np.shape(a)
print("Shape of the array:", c)

# Determine the size of the array
d = np.size(a)
print("Size of the array:", d)

Original array: [[[[2 3 4 5]]]]
Number of dimensions of the array: 4
Shape of the array: (1, 1, 1, 4)
Size of the array: 4


# Explanations:
  In this code, we import the NumPy library using import numpy as np.
We create a NumPy array a with multiple dimensions and a single element using the np.array() function. The array a contains nested lists representing different dimensions.

We then print the original array a using the print() function and the message "Original array:".

To determine the number of dimensions of the array a, we use the np.ndim() function. The np.ndim() function returns an integer representing the number of dimensions in the array. We assign this value to the variable b and print it using the print() function and the message "Number of dimensions of the array:".

To determine the shape of the array a, we use the np.shape() function. The np.shape() function returns a tuple representing the size of each dimension in the array. We assign this tuple to the variable c and print it using the print() function and the message "Shape of the array:".

To determine the size of the array a, we use the np.size() function. The np.size() function returns an integer representing the total number of elements in the array. We assign this value to the variable d and print it using the print() function and the message "Size of the array:".

In [ ]:
import numpy as np
a = np.array([[[2,3,4,5],[6,7,8,9]],[[11,12,13,14],[13,14,15,16]]])
print("Original array",a)
b = np.ndim(a)
print(b)
print()
c = np.shape(a)
print(c)
print()
d = np.size(a)
print(d)

Original array [[[ 2  3  4  5]
  [ 6  7  8  9]]

 [[11 12 13 14]
  [13 14 15 16]]]
3

(2, 2, 4)

16


In [ ]:
a = np.array([2,3,4,5],dtype = float)
print(a)


[2. 3. 4. 5.]


# Explanation code
In this code, we import the NumPy library using import numpy as np.
We create a NumPy array a using the np.array() function. The array a is initialized with the elements [2, 3, 4, 5]. The optional argument dtype=float specifies that the elements of the array should have the data type float.
We print the array a using the print() function. This statement displays the contents of the array a.

In [ ]:
a = np.array([2.3,3.4,4.5],dtype = complex)
print(a)

[2.3+0.j 3.4+0.j 4.5+0.j]


# Explanation code
In this code, we import the NumPy library using import numpy as np.
We create a NumPy array a using the np.array() function. The array a is initialized with the elements [2.3, 3.4, 4.5]. The optional argument dtype=complex specifies that the elements of the array should have the data type complex, which represents complex numbers.
We print the array a using the print() function. This statement displays the contents of the array a.

In [ ]:
a = np.array([2.3,3.4,4.5],dtype = str)
print(a)

['2.3' '3.4' '4.5']


# how to create one array convert in multiple dimenssional array

In [ ]:
a = np.array([2.3,3.4,4.5],ndmin = 5)
print(a)
b = np.shape(a)
print(b)

[[[[[2.3 3.4 4.5]]]]]
(1, 1, 1, 1, 3)


# check array data type and Shape

In [ ]:
import numpy as np
x = [[[1,'3',4,4,5,6]]]
a= np.array(x)
b=np.shape(a)
print(b)
print(a)
print("Array Data type : ", a.dtype)


(1, 1, 6)
[[['1' '3' '4' '4' '5' '6']]]
Array Data type :  <U21


# Array
* Create Array defferent type

Create Array defferent type

In [ ]:

import numpy as np
arr =np.array([[[[1,3,4,6]]]])
print(arr)
arr
print(type(arr))
a = type(arr)
print(a)
b=np.shape(arr)
print("array Shape=",b)
c= ndim(arr)
print("Number of dimensional array=",c)


[[[[1 3 4 6]]]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
array Shape= (1, 1, 1, 4)
Number of dimensional array= 4


# Other Example

In [ ]:
from numpy.core.fromnumeric import ndim

import numpy as np
arr =np.array([[[[1,3,4,6]]]])
print(arr)
arr
print(type(arr))
a = type(arr)
print(a)
b=np.shape(arr)
print("array Shape=",b ,arr.dtype)
c= ndim(arr)
print("Number of dimensional array=",c)


[[[[1 3 4 6]]]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
array Shape= (1, 1, 1, 4) int64
Number of dimensional array= 4


In the code, we import the NumPy library using import numpy as np. This allows us to use the functions and features of NumPy in our code.

In [5]:
import numpy as np
l=[]
for i in range(1,5):
  int_1=int(input("enter :"))
  l.append(int_1)


print(np.array(l))

enter :3
enter :2
enter :2
enter :2
[3 2 2 2]


Code Explanation:
The code snippet creates an empty list l and then uses a for loop to iterate from 1 to 4 (inclusive). Inside the loop, it prompts the user to enter a value using the input() function and converts it to an integer using the int() function. The obtained integer value is then appended to the list l using the append() method.
Finally, the np.array() function is used to create a NumPy array from the list l. This function takes the list as an argument and returns a NumPy array. The resulting array is printed using the print() function.
When you run the code, it will prompt you to enter four values. After you input the values, it will create a NumPy array l with those values and print it.

In [ ]:
ar3 = np.array([[1,2,3,4],[1,2,3,4]])
print(ar3)
print(np.ndim(ar3))
print("shape=",np.shape(ar3))

[[1 2 3 4]
 [1 2 3 4]]
2
shape= (2, 4)


In [ ]:
ar4=np.array([[1,2,3,4],[1,2,3,4]])
print(ar4)
print("dimnshial array=",np.ndim(ar4))

[[1 2 3 4]
 [1 2 3 4]]
dimnshial array= 2


In [ ]:
ar4=np.array([[[1,2,3,4],[1,2,3,4],[4,5,7,6]]])
print(ar4)
print("dimnshial array=",np.ndim(ar4))

[[[1 2 3 4]
  [1 2 3 4]
  [4 5 7 6]]]
dimnshial array= 3
