<a href="https://colab.research.google.com/github/eisakhan04/Numpy-Course/blob/main/Topic_17_Numpy_iterating.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Topic 17: Numpy iterating**

NumPy is a Python library used for numerical and scientific computing. It provides a powerful array object for efficiently storing and manipulating large arrays of data. When working with NumPy arrays, we often need to go through each element of the array and perform some computation or operation on it. This is called array iteration.

We can iterate over a NumPy array using loops such as for and while loops, or using built-in functions like nditer() and flat(). nditer() allows us to iterate over an array in a specific order, while flat() returns a one-dimensional iterator that iterates over all the elements of the array.

Efficient iteration over NumPy arrays is essential for fast and reliable code, especially when working with large datasets. Therefore, it's important to choose the right method of iteration that suits our needs and optimizes our code.

In [2]:
import numpy as np

a = np.array([2,3,5,7,6])
for x in a:
  print(x)

2
3
5
7
6


In [3]:
a = np.array([[2,3,5,7],[8,9,10,11],[12,13,14,15]])
for x in a:
  print(x)

[2 3 5 7]
[ 8  9 10 11]
[12 13 14 15]


In [7]:
a = np.array([[2,3,5,7],[8,9,10,11],[12,13,14,15]])
for x in np.nditer(a):
  print(x)

2
3
5
7
8
9
10
11
12
13
14
15


Explanation

It creates a two-dimensional NumPy array called "arr" with three rows and two columns. Each row contains two elements.

The for loop then iterates over each element in the array using the "np.nditer()" function. This function is used to iterate over multi-dimensional arrays in a specific order, which in this case is the default order (row-major).

The print statement inside the loop prints out each element of the array, one at a time, to the console.

So the output of this code would be:

1 2 3 4 5 6

Note that the elements are printed out in the order they are accessed by the iterator, which is row-major order in this case.

**nditer means**

where("nditer" is a term commonly used in programming, specifically in Python's NumPy library. It refers to a function that is used to iterate over arrays in a multidimensional manner. The "nd" in "nditer" stands for "n-dimensional", meaning that the function can handle arrays with any number of dimensions. The "iter" part of the name indicates that the function is used for iteration purposes, i.e., to traverse through the array elements one by one. The nditer function allows for various iteration behaviors such as specific order, skipping or changing elements, etc.)

**flipud meand flip and ud(upp&down)**

flipud means

wherer("flipud" is a term commonly used in programming, specifically in Python's NumPy library. It refers to a function that is used to flip or invert an array along its vertical axis, also known as the y-axis. The "ud" in "flipud" stands for "up-down", indicating that the function flips the array vertically. The flipud function can be used to reverse the order of rows in a 2-dimensional array or to flip the order of elements in a 1-dimensional array along the vertical axis.)

In [6]:
a = np.array([2,3,5,7,6])
for x in np.flipud(a):
  print(x)

6
7
5
3
2


In [ ]:
import numpy as np
arr = np.array([[1, 2], [3, 4], [5, 6]])
print("original array:",arr)
print()
for x in np.nditer(arr, order='F'):
  print(x)


**Explanation**

It creates a two-dimensional NumPy array called "arr" with three rows and two columns. Each row contains two elements.

The for loop uses the "np.nditer()" function to iterate over the array in column-major order. The 'F' parameter specifies that the order of iteration should be column-major, which means that the loop will iterate over each column first, and then move to the next column.

The print statement inside the loop prints out each element of the array, one at a time, to the console.

So the output of this code would be:

1 3 5 2 4 6

Note that the elements are printed out in the order they are accessed by the iterator, which is column-major order in this case.

In [11]:
import numpy as np
arr = np.array([[1, 2], [3, 4], [5, 6]])
for x in np.nditer(arr, order='C'):
  print(x)

1
2
3
4
5
6


**Explanation**

It creates a two-dimensional NumPy array called "arr" with three rows and two columns. Each row contains two elements.

The for loop uses the "np.nditer()" function to iterate over the array in row-major order. The 'C' parameter specifies that the order of iteration should be row-major, which means that the loop will iterate over each row first, and then move to the next row.

The print statement inside the loop prints out each element of the array, one at a time, to the console.

So the output of this code would be:

1 2 3 4 5 6

Note that the elements are printed out in the order they are accessed by the iterator, which is row-major order in this case. This is the default order for the iterator.

In [12]:

import numpy as np
arr = np.array([[1, 2], [3, 4], [5, 6]])
for x in np.nditer(arr, op_flags=['readwrite']):
  x[...] = 2 * x;
  print(x,end = ' ')

2 4 6 8 10 12 

**Explanation**

This is a Python code that uses the NumPy library. It defines a two-dimensional NumPy array called "arr" that contains three rows and two columns.

The code then uses a loop to iterate over all the elements in the array using the "np.nditer" function. The "op_flags=['readwrite']" argument specifies that the loop can both read and write to each element.

Inside the loop, each element is multiplied by 2 using the expression "2 * x", and then the updated value is stored back into the original element using the notation "x[...] = 2 * x".

Finally, the loop prints out each element in the updated array on a single line, separated by spaces, using the "print" function with the argument "end = ' '".

In [13]:
import numpy as np
arr = np.array([[1, 2], [3, 4], [5, 6]])
for x in np.nditer(arr, op_flags=['readwrite']):
  x[...] = x * 2
print(arr)

[[ 2  4]
 [ 6  8]
 [10 12]]


**Explanation**

This is a Python code that uses the NumPy library. It defines a two-dimensional NumPy array called "arr" that contains three rows and two columns.

The code then uses a loop to iterate over all the elements in the array using the "np.nditer" function. The "op_flags=['readwrite']" argument specifies that the loop can both read and write to each element.

Inside the loop, each element is multiplied by 2 using the expression "x * 2", and then the updated value is stored back into the original element using the notation "x[...] = x * 2".

Finally, after the loop is completed, the updated "arr" array is printed using the "print" function. This will show the updated values for each element in the array, where each element has been multiplied by 2.