<a href="https://colab.research.google.com/github/eisakhan04/Numpy-Course/blob/main/Topic_13_Numpy_Sorting_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Topic 13: Numpy Sorting Arrays**
1. sort() function
2. sort(a, axis = 0) Column wise arrangement axis = 0
3. sort(a, axis = 1) Rows wise arrangement axis = 1
4. argsort()
5. lexsort((a,b)) first array arrangement and compare to second array index wise
6.  np.partition() function

**1. sort() function**

In [ ]:
import numpy as np
a= np.array([[3,1,6,9,6,4,8,7,4],[5,2,5,6,4,3,4,6,8]])
b=np.sort(a)
print(b)

[[1 3 4 4 6 6 7 8 9]
 [2 3 4 4 5 5 6 6 8]]


**Explanation:**

The first line imports the NumPy library and assigns it the alias np. This is a common convention in Python code, as it makes the code more readable.

The second line creates a NumPy array called a. This array contains two rows, each of which contains 9 numbers. The numbers in the array are randomly generated.

The third line uses the np.sort() function to sort the elements in a in ascending order. The np.sort() function takes an array as input and returns a new array with the elements sorted.

The fourth line prints the sorted array b. The output of the print statement is a 2-dimensional array with 9 elements in each row. The elements in each row are sorted in ascending order.

**2. sort(a, axis = 0) Column wise arrangement axis = 0**

In [ ]:
import numpy as np
a= np.array([[3,1,6,9,6,4,8,7,4],[5,2,5,6,4,3,4,6,8]])
print("Orignal array :")
print(a)
print()
print(np.sort(a))
print()
b=np.sort(a, axis= 0) # Column wise sorted
print(b)

Orignal array :
[[3 1 6 9 6 4 8 7 4]
 [5 2 5 6 4 3 4 6 8]]

[[1 3 4 4 6 6 7 8 9]
 [2 3 4 4 5 5 6 6 8]]

[[3 1 5 6 4 3 4 6 4]
 [5 2 6 9 6 4 8 7 8]]


**Explanation:**

The first line imports the NumPy library and assigns it the alias np. This is a common convention in Python code, as it makes the code more readable.

The second line creates a NumPy array called a. This array contains two rows, each of which contains 9 numbers. The numbers in the array are randomly generated.

The third line prints the original array a. The output of the print statement is a 2-dimensional array with 9 elements in each row.

The fourth line uses the np.sort() function to sort the elements in a in ascending order. The np.sort() function takes an array as input and returns a new array with the elements sorted.

The fifth line prints the sorted array. The output of the print statement is a 2-dimensional array with 9 elements in each row. The elements in each row are sorted in ascending order.

**The sixth line uses the np.sort() function to sort the elements in a along the axis=0. This means that the elements in each column will be sorted in ascending order.**

The seventh line prints the sorted array. The output of the print statement is a 2-dimensional array with 9 elements in each row. The elements in each column are sorted in ascending order.

**3. sort(a, axis = 1) Rows wise arrangement axis = 1**

In [ ]:
import numpy as np
a= np.array([[3,1,6,9,6,4,8,7,4],[5,2,5,6,4,3,4,6,8]])
print("Orignal array :")
print(a)
print()
print(np.sort(a))
print()
b=np.sort(a, axis= 1) # Rows  wise sorted
print(b)

Orignal array :
[[3 1 6 9 6 4 8 7 4]
 [5 2 5 6 4 3 4 6 8]]

[[1 3 4 4 6 6 7 8 9]
 [2 3 4 4 5 5 6 6 8]]

[[1 3 4 4 6 6 7 8 9]
 [2 3 4 4 5 5 6 6 8]]


**Explanation:**

The first line imports the NumPy library and assigns it the alias np. This is a common convention in Python code, as it makes the code more readable.

The second line creates a NumPy array called a. This array contains two rows, each of which contains 9 numbers. The numbers in the array are randomly generated.

The third line prints the original array a. The output of the print statement is a 2-dimensional array with 9 elements in each row.

The fourth line uses the np.sort() function to sort the elements in a in ascending order. The np.sort() function takes an array as input and returns a new array with the elements sorted.

The fifth line prints the sorted array. The output of the print statement is a 2-dimensional array with 9 elements in each row. The elements in each row are sorted in ascending order.

**The sixth line uses the np.sort() function to sort the elements in a along the axis=1. This means that the elements in each row will be sorted in ascending order.**

The seventh line prints the sorted array. The output of the print statement is a 2-dimensional array with 9 elements in each row. The elements in each row are sorted in ascending order.

# **Rows wise sorted in descending order**

In [ ]:
import numpy as np

a = np.array([[3, 1, 6, 9, 6, 4, 8, 7, 4], [5, 2, 5, 6, 4, 3, 4, 6, 8]])

print("Orignal array :")
print(a)
print()

print(np.sort(a))
print()

b = np.sort(a, axis=1)[::-1]  # Rows wise sorted in descending order
print(b)

Orignal array :
[[3 1 6 9 6 4 8 7 4]
 [5 2 5 6 4 3 4 6 8]]

[[1 3 4 4 6 6 7 8 9]
 [2 3 4 4 5 5 6 6 8]]

[[2 3 4 4 5 5 6 6 8]
 [1 3 4 4 6 6 7 8 9]]


**`Explan:`**

The code is similar to the code you provided, except that we have added the [::-1] slice to the np.sort() function. The [::-1] slice reverses the order of the elements in the array, which results in the array being sorted in descending order.



**4. argsort() /argument sort function:**

The numpy.argsort() function is a NumPy method used to perform an indirect sort on a NumPy array. It returns an array of indices that would sort the input array in ascending order by default, but can also sort them in descending order if specified.

In [ ]:
import numpy as np
a = np.array([3,2,1,4])
b = np.sort(a)
print(b)
print()
c = np.argsort(a)
print(c)

[1 2 3 4]

[2 1 0 3]


**Explanation:**

The next line of code uses the np.argsort() function to return an array of indices that would sort the array a. The np.argsort() function returns an array of the same shape as a, with the elements in sorted order. The code then prints the array of indices.

In [ ]:
import numpy as np
a = np.array([3,2,1,4])
b = np.sort(a)
print(b)
print()
c = np.argsort(b)
print(c)

[1 2 3 4]

[0 1 2 3]


#**5: lexsort((a,b)) function:**

**first array arrangement and compare to second array index wise**

The numpy.lexsort() function is a NumPy function that performs an indirect sort on multiple keys. It takes a sequence of arrays and returns an array of indices that can be used to index into the original arrays to obtain a sorted result. The sorting is performed on the last key first, then the second-last key, and so on, until the first key is sorted.

The syntax for the numpy.lexsort() function is:

numpy.lexsort(keys, axis=-1)

where keys is a sequence of arrays that will be used as the sorting keys, and axis specifies the axis along which to sort. By default, axis=-1, which means that the last axis is sorted.

In [1]:
import numpy as np
a = np.array([3,2,1,4])
b = np.array([4,1,3,2])
c=np.lexsort((a,b))
print(c)

[1 3 2 0]


The lexicographical sort is determined by comparing the elements in the order of b first and then breaking ties with a. In this example, when comparing the elements in b, [4, 1, 3, 2], the sorted order would be [1, 2, 3, 4]. And for elements with equal values in b, we consider the corresponding elements in a, which results in the final sorted arrays as shown above.