<a href="https://colab.research.google.com/github/onlyone11s/Numpy-Course/blob/main/Topic_06_Trigonometric_Function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Topic 06: Trigonometric Function**

Trigonometric functions are mathematical functions that are used to calculate the values of angles in a triangle. NumPy provides a number of trigonometric functions that can be used to perform various mathematical operations involving angles.

Here are some of the commonly used trigonometric functions in NumPy:

numpy.sin(x): This function returns the sine of x, where x is an angle in radians.

numpy.cos(x): This function returns the cosine of x, where x is an angle in radians.

numpy.tan(x): This function returns the tangent of x, where x is an angle in radians.

numpy.arcsin(x): This function returns the inverse sine of x, where x is a value between -1 and 1.

numpy.arccos(x): This function returns the inverse cosine of x, where x is a value between -1 and 1.

numpy.arctan(x): This function returns the inverse tangent of x, where x is a value between -infinity and infinity.

All of these functions take the angle as an argument in radians. If you have an angle in degrees, you can convert it to radians by multiplying it by pi/180. For example, to calculate the sine of an angle of 45 degrees, you would use the following code:

makefile Copy code import numpy as np angle_degrees = 45 angle_radians = angle_degrees * np.pi / 180 sin_value = np.sin(angle_radians) The result would be sin_value = 0.7071067811865476, which is the sine of 45 degrees in radians.

**Alegbraic Function pi = 3.1416**

**Trigonometric pi = 180**

**1.1: Convert Degree to Radian**

**Degree to Radian (Multiplication 0.01745)**

In [ ]:
import numpy as np
deg = 270
rad = np.deg2rad(deg)
print(rad)

4.71238898038469


In [ ]:
import numpy as np
deg = [30,60,90]
rad = np.deg2rad(deg)
print(rad)

[0.52359878 1.04719755 1.57079633]


**1.2:Radian to Degree**

**Radian to Degree (Put pi = 180)**

In [ ]:
rad = np.pi/2
deg = np.rad2deg(rad)
print(deg)

90.0


In [ ]:
rad = np.pi/21
deg = np.rad2deg(rad)
print(deg)

8.571428571428571


In [ ]:
import numpy as np
rad = np.array([np.pi/2,np.pi/3,np.pi/4])
deg =np.rad2deg(rad)
print(deg)

[90. 60. 45.]


**1.3: Sin() Function**

In [ ]:
a = np.array([np.pi/2, np.pi/3,np.pi/4])
deg =np.rad2deg(a)
print(deg)
print("Sin() of values")
b = np.sin(a)
print(b)


[90. 60. 45.]
Sin() of values
[1.         0.8660254  0.70710678]


**radian to degree and sin and then sin inverse with the using of 'arc'**

**Degree val = 0.01745**


**Radian val = 57.2956**

**Sin() Radian to degree**

In [ ]:
a = np.array([np.pi/2,np.pi/3,np.pi/4])
print("original array in Algebraic")
print(a)
print()
deg =np.rad2deg(a)
print(deg)
print()
print("Sin() of values")
b = np.sin(a)
print(b)
print()
print("inverse function")
c = np.arcsin(b)
print(c)

original array in Algebraic
[1.57079633 1.04719755 0.78539816]

[90. 60. 45.]

Sin() of values
[1.         0.8660254  0.70710678]

inverse function
[1.57079633 1.04719755 0.78539816]


**Sin() Degree to Radian**

In [ ]:
a = np.array([60, 45 , 90 ])
print("original array in Algebraic")
print(a)
print()
rad =np.deg2rad(a)
print(rad)
print()
print("Sin() of values")
b = np.sin(rad)
print(b)
print()
print("inverse function")
c = np.arcsin(b)
print(c)

original array in Algebraic
[60 45 90]

[1.04719755 0.78539816 1.57079633]

Sin() of values
[0.8660254  0.70710678 1.        ]

inverse function
[1.04719755 0.78539816 1.57079633]


**Cos() Radian to degree**

In [ ]:
a = np.array([np.pi/6 ,np.pi/3,np.pi/4])
print("original array in Algebraic")
print(a)
print()
deg =np.rad2deg(a)
print(deg)
print()
print("Cos() of values")
b = np.cos(a)
print(b)
print()
print("inverse function")
c = np.arccos(b)
print(c)

original array in Algebraic
[0.52359878 1.04719755 0.78539816]

[30. 60. 45.]

Cos() of values
[0.8660254  0.5        0.70710678]

inverse function
[0.52359878 1.04719755 0.78539816]


**Cos() Degree to Radian**

In [ ]:
a = np.array([60, 45 , 70 ])
print("original array in Algebraic")
print(a)
print()
rad =np.deg2rad(a)
print(rad)
print()
print("Cos of values")
b = np.cos(rad)
print(b)
print()
print("inverse function")
c = np.arccos(b)
print(c)

original array in Algebraic
[60 45 70]

[1.04719755 0.78539816 1.22173048]

Cos of values
[0.5        0.70710678 0.34202014]

inverse function
[1.04719755 0.78539816 1.22173048]


# degree to redian

In [2]:
import numpy as np
deg =np.array([40,30,20,77])
print("Orignal value:",deg)
print()
a=np.deg2rad(deg)
print("Degree to redian:Degree to Radian (Multiplication 0.01745)::",a)

Orignal value: [40 30 20 77]

Degree to redian:Degree to Radian (Multiplication 0.01745):: [0.6981317  0.52359878 0.34906585 1.34390352]


# Redian to Degree

In [15]:
rad=np.array([np.pi/5,np.pi/77,np.pi/99,np.pi/23])
print("Orignal value of Radian:Alegbraic Function pi = 3.1416::",rad)
a=np.rad2deg(rad)
print("Radian value:Trigonometric pi = 180:: ",a)

Orignal value of Radian:Alegbraic Function pi = 3.1416:: [0.62831853 0.0407999  0.03173326 0.13659098]
Radian value:Trigonometric pi = 180::  [36.          2.33766234  1.81818182  7.82608696]


# Sin() Function with degree to radin

In [14]:
a=np.array([20,88,99,33])
rad=np.deg2rad(a)
print("Degree to Radian (Multiplication 0.01745)::",rad)
sin=np.sin(rad)
print("sin Answer:",sin)
inverse=np.arcsin(sin)
print("inverse:",inverse)

Degree to Radian (Multiplication 0.01745):: [0.34906585 1.53588974 1.72787596 0.57595865]
sin Answer: [0.34202014 0.99939083 0.98768834 0.54463904]
inverse: [0.34906585 1.53588974 1.41371669 0.57595865]


# Sin() Function radian to degree

In [13]:
import numpy as np
a = np.array([np.pi/6,np.pi/4,np.pi/2,np.pi/5])
print("use by this pi value 3.1416:",a)
deg=np.rad2deg(a)
print("180 devid by:",deg)
sin=np.sin(a)
print("Sin Value:",sin)
inv=np.arcsin(sin)
print("inverse:",inv)

use by this pi value 3.1416: [0.52359878 0.78539816 1.57079633 0.62831853]
180 devid by: [30. 45. 90. 36.]
Sin Value: [0.5        0.70710678 1.         0.58778525]
inverse: [0.52359878 0.78539816 1.57079633 0.62831853]


# cos() function Degree to radin

In [12]:
b=np.array([80,40,60,35])
rad=np.deg2rad(b)
print("degree to radin function:",rad)
cos=np.cos(rad)
print(cos)
invers=np.arccos(cos)
print(invers)

degree to radin function: [1.3962634  0.6981317  1.04719755 0.61086524]
[0.17364818 0.76604444 0.5        0.81915204]
[1.3962634  0.6981317  1.04719755 0.61086524]


# cos() function radian to degree

In [11]:
e = np.array([np.pi/6,np.pi/1,np.pi/5,np.pi/8])
print(e)
deg=np.rad2deg(e)
print(deg)
print("cos value:")
Cos=np.cos(e)
print(Cos)
print("inverse od cos:")
invee=np.arccos(Cos)
print(invee)

[0.52359878 3.14159265 0.62831853 0.39269908]
[ 30.  180.   36.   22.5]
cos value:
[ 0.8660254  -1.          0.80901699  0.92387953]
inverse od cos:
[0.52359878 3.14159265 0.62831853 0.39269908]


# tan() function degree to radin

In [10]:
a = np.array([30,50,20,10])
rad=np.deg2rad(a)
print(rad)
A=np.tan(rad)
print("tan:",A)
S=np.arctan(A)
print("inverse tan:",S)

[0.52359878 0.87266463 0.34906585 0.17453293]
tan: [0.57735027 1.19175359 0.36397023 0.17632698]
inverse tan: [0.52359878 0.87266463 0.34906585 0.17453293]


# tan() function radain to degree

In [9]:
a = np.array([np.pi/4,np.pi/8,np.pi/7])
print(a)
deg=np.rad2deg(a)
print(rad)
A=np.tan(a)
print("tan:",A)
S=np.arctan(A)
print("inverse tan:",S)

[0.78539816 0.39269908 0.44879895]
[0.52359878 0.87266463 0.34906585 0.17453293]
tan: [1.         0.41421356 0.48157462]
inverse tan: [0.78539816 0.39269908 0.44879895]


In [16]:

import numpy as np
a = np.array([2*np.pi/2,2*np.pi/3,0])
print("Original array:", a)
print()
b = np.cos(a)
print("Cosine Values:" ,b)


Original array: [3.14159265 2.0943951  0.        ]

Cosine Values: [-1.  -0.5  1. ]
