<a href="https://colab.research.google.com/github/onlyone11s/Numpy-Course/blob/main/Topic_04_Numpy_Reshaping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Topic 04: Numpy Reshaping**

Numpy is a popular Python library used for numerical computing. It provides powerful tools for array manipulation, which includes reshaping an array. Reshaping is the process of changing the shape or dimensions of an existing array without changing the data within it.

**(01) Reshaping One-Dimension Array**

In [ ]:
import numpy as np
a=np.array([5,6,7,8,9,8,9,3])
print(a)
print()
b= a.reshape(4,2)
print(b)

#**Explanation**
In this part, we import the NumPy library and create an array a containing eight elements: [5, 6, 7, 8, 9, 8, 9, 3]. Then, we print the array a.
In this part, we use the reshape() function to change the shape of the array a. We pass the reshape() function two arguments: 4 and 2, which means we want to reshape a into a 4x2 array.
The reshape() function rearranges the elements of the original array a to form a new array b with the desired shape. The new array will have 4 rows and 2 columns.

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6])
print(a)
print()
b = a.reshape(3,2,1)
print(b)

[1 2 3 4 5 6]

[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]


**(02) Reshaping 2- Dimensional Arry**

In [ ]:
import numpy as np
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a)
print()
b = a.reshape(3,4)
print(b)

In [ ]:
import numpy as np
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a)
print(a.reshape(3,2,2))


#**Explanation**
In this part, we import the NumPy library and create a** 2D array **a. The array a has two rows and six columns.
Next, we use the **reshape()** function to change the shape of the array a. **We pass the reshape() function three arguments: 3, 2, and 2. This means we want to reshape a into a 3x2x2 array.**
The reshape() function rearranges the elements of the original 2D array a to form a new 3D array with the desired shape. The new array has three "blocks," each containing two rows and two columns.

The first "block" consists of the elements [1, 2, 3, 4].
The second "block" consists of the elements [5, 6, 7, 8].
The third "block" consists of the elements [9, 10, 11, 12].
Each block is formed by extracting two rows and two columns from the original array a while maintaining their order. This results in the final 3x2x2 array shown in the output.

In [ ]:
import numpy as np
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a)
print()
b = a.reshape(3,2,2)
print(b)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
import numpy as np
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a)
print()
b = a.reshape(6,2,1)
print(b)

In [ ]:
import numpy as np
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a)
print()
b = a.reshape(1,6,2)
print(b)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]]]


#**(03) Reshaping 3- Dimensional Arry**
In this part, we import the NumPy library and create a 3D array a. The array a has two "blocks," each containing two rows and six columns.

In [ ]:
import numpy as np
a = np.array([[[1,2,3,4,5,6],[7,8,9,10,11,12]],[[7,3,0,6,2,1],[56,8,77,43,11,66]]])
print(a)
print("Size=", np.size(a))
b = a.reshape(6,4,1)
print(b)

#**Explanation:**
The total number of elements in the 3D array a is 24. The array a consists of two "blocks," each having two rows and six columns, resulting in a total of 4 rows and 12 columns in the entire array. Thus, there are 24 elements in the array a.

Finally, we use the reshape() function to change the shape of the array a. We pass the reshape() function three arguments: 6, 4, and 1. This means we want to reshape a into a 3D array with 6 "blocks," each containing 4 rows and 1 column.