# **Topic 10: numpy matlib**

The matlib function in NumPy is a legacy function that provides a MATLAB-like interface to NumPy arrays. It is not recommended to use matlib in new code, as it is not as efficient as using the NumPy functions directly. However, it can be useful for porting code from MATLAB to NumPy.

The matlib function provides a number of functions that are similar to the MATLAB functions of the same name. For example, the matlib.rand() function returns a matrix of random numbers, and the matlib.eye() function returns the identity matrix


The matlib function in NumPy is a legacy function that provides a MATLAB-like interface to NumPy arrays. It is not recommended to use matlib in new code, as it is not as efficient as using the NumPy functions directly. However, it can be useful for porting code from MATLAB to NumPy.

The matlib function provides a number of functions that are similar to the MATLAB functions of the same name. For example, the matlib.rand() function returns a matrix of random numbers, and the matlib.eye() function returns the identity matrix.

The matlib function is not part of the NumPy standard library, so it must be imported explicitly. To do this, you can use the following code:

Python
import numpy.matlib as matlib
Use code with caution. Learn more
Once you have imported the matlib function, you can use it to create and manipulate NumPy arrays. For example, the following code creates a matrix of random numbers and prints it to the console:

Python
import numpy.matlib as matlib

matrix = matlib.rand(5, 5)
print(matrix)
Use code with caution. Learn more
This code will print a 5x5 matrix of random numbers to the console.

As I mentioned earlier, it is not recommended to use the matlib function in new code. However, it can be useful for porting code from MATLAB to NumPy. If you are not sure whether or not to use matlib, it is best to consult the NumPy documentation.

**Here are some of the most commonly used matlib functions:**

1. matlib.rand(): Returns a matrix of random numbers.
2. matlib.eye(): Returns the identity matrix.
3. matlib.zeros(): Returns a matrix of zeros.
4. matlib.ones(): Returns a matrix of ones.
5. matlib.diag(): Returns the diagonal of a matrix.
6. matlib.repmat(): Repeats a matrix a specified number of times.

# others matlib Function 
* numpy.matlib.empty() function
* numpy.matlib.zeros() function
* numpy.matlib.ones() function
* numpy.matlib.eye() function
* numpy.matlib.rand() function

# numpy.matlib.empty() function

In [9]:
import numpy as np
import numpy.matlib
a= np.matlib.empty((1,2))
print(a)


[[1.42598117e-311 3.79442416e-321]]


In [10]:
import numpy as np
import numpy.matlib
a= np.matlib.empty((1,2),dtype=complex)
print(a)

[[2.12199579e-314+1.42598117e-311j 3.55727265e-321+3.79442416e-321j]]


# numpy.matlib.zeros() function

In [12]:
import numpy as np 
import numpy.matlib
b=np.matlib.zeros((7,8))
print(b)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [13]:
import numpy as np 
import numpy.matlib
b=np.matlib.zeros((7,8),dtype=int)
print(b)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


#  numpy.matlib.ones() function

In [16]:
import numpy as np
import numpy.matlib

c=np.matlib.ones((3,5))
print(c)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [17]:
import numpy as np
import numpy.matlib

c=np.matlib.ones((3,5), dtype=str)
print(c)

[['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']]


# numpy.matlib.eye() function or identity function

In [19]:
import numpy as ap
import numpy.matlib

x= np.matlib.eye(6,6)
print(x)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


# numpy.matlib.rand() function

In [21]:
import numpy as np
import numpy.matlib
s =np.matlib.rand(3,4)
print(s)

[[0.02563723 0.67923956 0.68441493 0.19825748]
 [0.92236672 0.53933624 0.7981539  0.21502787]
 [0.36396171 0.14599641 0.04678745 0.86133661]]


# matlib.diag() function

In [25]:
import numpy as np
import numpy.matlib
s =np.matlib.diag((3,6,6,7,2))
print(s)

[[3 0 0 0 0]
 [0 6 0 0 0]
 [0 0 6 0 0]
 [0 0 0 7 0]
 [0 0 0 0 2]]


# matlib.repmat() function

In [ ]:
import numpy as np
import numpy.matlib
s =np.matlib.repmat(3,2)
print(s)