<a href="https://colab.research.google.com/github/eisakhan04/Numpy-Course/blob/main/Topic_15_Numpy_array_from_existing_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Topic 15:Numpy array from existing data**

**1. numpy. asarray**
Topic 15 = Numpy Array From Existing Data
NumPy is a powerful Python library used for scientific computing and data analysis. One of the key features of NumPy is its ability to create arrays of data, which can be used for various mathematical operations. NumPy arrays can be created from existing data, such as Python lists or tuples, by using the np.array() function.

To create a NumPy array from an existing Python list, you first need to import the NumPy library. This can be done by running the following code:

import numpy as np

Next, you can create a NumPy array from a list by passing the list as an argument to the np.array() function. For example, the following code creates a NumPy array from a Python list of integers:

my_list = [1, 2, 3, 4, 5] my_array = np.array(my_list)

You can also create a NumPy array from a Python tuple using the same approach. Once you have created a NumPy array, you can perform various mathematical operations on it, such as addition, subtraction, multiplication, and division. NumPy also provides many built-in functions for performing statistical calculations on arrays.

NumPy provides us the way to create an array by using the existing data.

1. numpy.asarray().
2. numpy.frombuffer().
3. numpy.fromiter()
Type 1. numpy.asarray function

This function is used to create an array by using the existing data in the form of lists, or tuples. This function is useful in the scenario where we need to convert a python sequence into the numpy array object.

The NumPy asarray() function is a method that converts a given input, such as a list or tuple, into a NumPy array. The resulting array will have the same data type and shape as the input data.

The asarray() function is useful when you want to ensure that your input data is a NumPy array, regardless of its original format. For example, if you have a list of numbers and you want to perform mathematical operations on it using NumPy functions, you can convert it to a NumPy array using asarray().

Here's the syntax for the asarray() function:

numpy.asarray(a, dtype=None, order=None)

a: The input data to be converted to a NumPy array. dtype: The desired data type of the resulting NumPy array. If not specified, the data type of the input data will be used. order: Specifies the memory layout of the resulting array. If not specified, NumPy will use 'C' (row-major) order by default.

Example 01: Creating an array from a list

In [ ]:
import numpy as np
a = [2,3,4,5]
b = np.asarray(a)
print(b)

[2 3 4 5]


**Tupple convert into array by the using of asarray**

In [ ]:
a = (2,3,4,5)
b = np.asarray(a)
print(b)

[2 3 4 5]


In [ ]:
a = np.array((2,3,4,5))
print(a)

[2 3 4 5]


In [1]:
import numpy as np
my_string = "1 2 3 4 5"
arr = np.asarray(my_string.split(), dtype=int)
print(arr)

[1 2 3 4 5]


In [ ]:
a = [2,3,4,5]
b = np.asarray(a,dtype=complex)
print(b)

[2.+0.j 3.+0.j 4.+0.j 5.+0.j]


**Type 2. numpy.frombuffer**

numpy.frombuffer is a NumPy function that creates a new one-dimensional array from an object that exposes the buffer interface. "Exposing the buffer interface means that an object provides a way to access its data in a raw, memory-efficient manner. This allows other objects or functions to access the data directly without the need for any additional copying or conversion, which can be especially useful for large amounts of data".

The numpy.frombuffer function takes two arguments: buffer and dtype. buffer is the object that exposes the buffer interface, while dtype specifies the data type of the returned array.

For example, if buffer is a bytes object containing the binary representation of an array of 32-bit integers, and dtype is set to 'int32', then numpy.frombuffer(buffer, dtype='int32') will return a new NumPy array containing the integers.

**This function can be useful when working with binary data, such as data stored in files or transmitted over networks.**

In [ ]:
import numpy as np
# Create a bytes object with integer data
data_bytes = b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00'

# Convert the bytes object to a NumPy array with a custom data type (dtype) and an offset
numpy_array = np.frombuffer(data_bytes, dtype=np.int32)
print(numpy_array)


[1 2 3]


In [ ]:
import numpy as np
# Create a bytes object with integer data
data_bytes = b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00'

# Convert the bytes object to a NumPy array with a custom data type (dtype) and an offset
numpy_array = np.frombuffer(data_bytes, dtype=np.uint8).reshape(4,3)
print(numpy_array)

[[1 0 0]
 [0 2 0]
 [0 0 3]
 [0 0 0]]


In [ ]:
# Example 03: Convert a string to a 1-dimensional array of characters:

import numpy as np
# create a string
s = 'hello'
# convert string to numpy array
arr = np.frombuffer(s.encode(), dtype='S1')
print(arr)

**Type 03: numpy.fromiter:**

numpy.fromiter is a NumPy function that creates a new NumPy array from an iterable object like a list or a generator. It takes two arguments: the iterable object, and the data type of the resulting NumPy array. This function is useful when we have a large amount of data that we don't want to store in a temporary list or array before creating a NumPy array. Instead, we can generate the data on-the-fly using an iterable object and create the NumPy array directly from it.

In [2]:
import numpy as np
a = [2,3,4,5]
b = np.fromiter(a,dtype = complex)
print(b)

[2.+0.j 3.+0.j 4.+0.j 5.+0.j]


In [7]:
import numpy as np
my_gen = (x**2 for x in range(6))
print(my_gen)
print()
my_array = np.fromiter(my_gen, dtype=int)
print(my_array)

<generator object <genexpr> at 0x7c77c1390b30>

[ 0  1  4  9 16 25]


In [5]:
import numpy as np
my_gen = (complex(x, x+1) for x in range(3))
print(my_gen)
print()
my_array = np.fromiter(my_gen, dtype=complex)
print(my_array)

<generator object <genexpr> at 0x7c77c13907b0>

[0.+1.j 1.+2.j 2.+3.j]


In [8]:
import numpy as np
my_range = range(5)
my_array = np.fromiter(my_range, dtype=np.uint8)
print(my_array)

[0 1 2 3 4]


**Explanation:**

This code creates a range object called "my_range" with values from 0 up to, but not including, 5.

Next, the code uses NumPy's "fromiter" function to create a one-dimensional array called "my_array" from the values in "my_range". The "dtype=np.uint8" argument specifies that the data type of the array should be unsigned 8-bit integers.

Finally, the code prints the contents of "my_array" to the console using the "print" function. The output of this code will be an array of unsigned 8-bit integers with the values [0 1 2 3 4].