<a href="https://colab.research.google.com/github/eisakhan04/Numpy-Course/blob/main/Topic_18_%3D_NumPy_Data_Types.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


#**Topic 18 = NumPy Data Types:**

NumPy is a Python library that is used for scientific computing, and it provides a powerful array data type called ndarray. The ndarray can be used to store homogeneous data (i.e., data of the same type) in a multidimensional array.

NumPy supports a range of data types that can be used with the ndarray. These data types are specified using a single character code, which is used as a shorthand notation for the data type. Here are some of the most commonly used data types in NumPy:

1.int: integer( used to represent integer numbers. e.g. -1, -2, -3)

2. float: floating-point number(used to represent real numbers. e.g. 1.2, 42.42)

3. complex: complex number( used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j)

4. bool: Boolean (True or False)

5. object: Python object

6. string_: fixed-length string( used to represent text data, the text is given under quote marks. e.g. "ABCD")

7. unicode_: fixed-length Unicode string

Each data type has a corresponding bit depth, which determines the range of values that can be represented by the data type. For example, an int16 can represent integers between -32,768 and 32,767, while an int64 can represent integers between -9,223,372,036,854,775,808 and 9,223,372,036,854,775,807.

NumPy also supports structured data types, which allow you to create arrays with fields that can be different data types. Structured data types are specified using a dictionary with keys that represent field names and values that represent the data type of each field.

1. int8: 8-bit signed integer (-128 to 127)
2. uint8: 8-bit unsigned integer (0 to 255)
3. int16: 16-bit signed integer (-32768 to 32767)
4. uint16: 16-bit unsigned integer (0 to 65535)
5. int32: 32-bit signed integer (-2147483648 to 2147483647)
6. uint32: 32-bit unsigned integer (0 to 4294967295)
7. int64: 64-bit signed integer (-9223372036854775808 to 7. 9223372036854775807)
8. uint64: 64-bit unsigned integer (0 to 18446744073709551615)
9. float16: 16-bit floating-point number
10. float32: 32-bit floating-point number
11. float64: 64-bit floating-point number
12. complex64: 64-bit complex number
13. complex128: 128-bit complex number
14. bool: Boolean (True or False)
15. object: Python object type, can hold any data type

These data types can be used to define the type of elements in a NumPy array or matrix, and they have different ranges and precision depending on the data type. It's important to choose the appropriate data type based on the type of data being stored to optimize memory usage and computation speed.

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

1. i - integer
2. b - boolean
3. u - unsigned integer
4. f - float
5. c - complex float
6. m - timedelta
7. M - datetime
8. O - object
9. S - string
10. U - unicode string
11.V - fixed chunk of memory for other type ( void )



**Example 01: Get the data type of an array object:**

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int64


**Explanation**

The code creates a NumPy array named "arr" with the values [1, 2, 3, 4].

The "dtype" property of a NumPy array specifies the data type of the array elements.

The "print(arr.dtype)" statement prints out the data type of the elements in the "arr" array, which is likely to be "int64" (64-bit integer) in this case, as the default data type for integers in NumPy is "int64".

**Example 02: Get the data type of an array containing strings:**

In [2]:
import numpy as np
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


**Explanation**

The given code creates a NumPy array called "arr" with the values ['apple', 'banana', 'cherry'].

The "dtype" property of a NumPy array specifies the data type of the array elements.

Since the elements in the "arr" array are strings, the "print(arr.dtype)" statement will output the data type as "string" or "object", depending on the version of NumPy being used.

**Example 03: Create an array with data type 4 bytes integer:**

In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)



[1 2 3 4]
int32


**Explanation**

The given code creates a NumPy array called "arr" with the values [1, 2, 3, 4], and explicitly specifies the data type of the elements to be "i4" using the "dtype" parameter.

The "i4" data type refers to a 32-bit integer, meaning each element in the array is represented using 4 bytes (32 bits) of memory.

The "print(arr)" statement outputs the values of the "arr" array, which will be [1, 2, 3, 4].

The "print(arr.dtype)" statement outputs the data type of the elements in the "arr" array, which will be "int32" as "i4" is an alias for 32-bit integer data type in NumPy.

**Example 04: Change data type from float to integer by using 'i' as parameter value:**



In [5]:

import numpy as np
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)


[1 2 3]
int32


**Explanation**

The given code creates a NumPy array called "arr" with the values [1, 2, 3, 4], and explicitly specifies the data type of the elements to be "i4" using the "dtype" parameter.

The "i4" data type refers to a 32-bit integer, meaning each element in the array is represented using 4 bytes (32 bits) of memory.

The "print(arr)" statement outputs the values of the "arr" array, which will be [1, 2, 3, 4].

The "print(arr.dtype)" statement outputs the data type of the elements in the "arr" array, which will be "int32" as "i4" is an alias for 32-bit integer data type in NumPy.

**Example 05: Change data type from float to integer by using int as parameter value:**

In [7]:
import numpy as np
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int64


**Explanation**

This code creates a NumPy array called arr with three decimal numbers: 1.1, 2.1, and 3.1.

The second line of code, newarr = arr.astype(int), creates a new NumPy array called newarr by converting the data type of the original arr array to integers. This is done using the astype method with the argument int, which specifies that the data type of the new array should be integer.

The third line of code, print(newarr), outputs the contents of the newarr array, which will be the integer equivalents of the decimal numbers in arr. In this case, the output will be [1 2 3].

The fourth line of code, print(newarr.dtype), outputs the data type of the newarr array, which will be int32 in this case.

**Example 06: Change data type from integer to boolean:**

In [8]:

import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


**Example 01: Create an array with data type string:**

In [9]:

import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


**Explanation**

The given code creates a NumPy array named "arr" which contains four elements [1, 2, 3, 4]. The "dtype='S'" parameter is used to specify the data type of the array elements as "S", which stands for string.

When we print the array using the first print statement, it will display [b'1', b'2', b'3', b'4'] because we specified the data type as "S" and it represents each element as a byte.

The second print statement outputs the data type of the array elements, which will display "S1" because we specified the data type as "S" and it takes up one byte of memory. Therefore, each element in the array is represented using one byte.

In [1]:

import numpy as np
# int8
x = np.array([1, 2, 3], dtype=np.int8)
print(x)

[1 2 3]


In [2]:
import numpy as np
# uint8
x = np.array([255, 128, 0], dtype=np.uint8)
print(x)


[255 128   0]


In [3]:

import numpy as np
# int16
x = np.array([-32768, 0, 32767], dtype=np.int16)
print(x)

[-32768      0  32767]


In [ ]:

import numpy as np
# uint16
x = np.array([65535, 32768, 0], dtype=np.uint16)
print(x)


In [ ]:

import numpy as np
# int32
x = np.array([-2147483648, 0, 2147483647], dtype=np.int32)
print(x)

In [ ]:

import numpy as np
# uint32
x = np.array([4294967295, 2147483648, 0], dtype=np.uint32)
print(x)

In [9]:
import numpy as np
# float64
x = np.array([1.0, 2.0, 3.0], dtype=np.float64)
print(x)


import numpy as np
# complex64
x = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex64)
print(x)


[1. 2. 3.]
[1.+2.j 3.+4.j 5.+6.j]


In [10]:
 import numpy as np
# object
x = np.array([1, "two", [3, 4, 5]], dtype=np.object)
print(x)

[1 'two' list([3, 4, 5])]


<ipython-input-10-c8d24da5656e>:3: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array([1, "two", [3, 4, 5]], dtype=np.object)


In [6]:
import numpy as np
# bool
x = np.array([True, False, True], dtype=np.bool)
print(x)


[ True False  True]


<ipython-input-6-b41595be7916>:3: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array([True, False, True], dtype=np.bool)


In [7]:
import numpy as np
# complex128
x = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print(x)

[1.+2.j 3.+4.j 5.+6.j]


In [8]:

import numpy as np
# int64
x = np.array([-9223372036854775808, 0, 9223372036854775807], dtype=np.int64)
print(x)

[-9223372036854775808                    0  9223372036854775807]


In [ ]:

import numpy as np
# float32
x = np.array([1.0, 2.0, 3.0], dtype=np.float32)
print(x)

In [ ]:

import numpy as np
# uint64
x = np.array([18446744073709551615, 9223372036854775808, 0], dtype=np.uint64)
print(x)

In [ ]:
import numpy as np
# float16
x = np.array([1.0, 2.0, 3.0], dtype=np.float16)
print(x)
