<a href="https://colab.research.google.com/github/onlyone11s/Numpy-Course/blob/main/Topic_03_Numpy_array_index.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Topic 03: Numpy array index**
NumPy is a popular Python library used for scientific computing, particularly for numerical operations and data analysis. One of the most important features of NumPy is its powerful array indexing capabilities.

Array indexing refers to the way in which elements of an array are selected and manipulated. In NumPy, arrays can be indexed using various methods, such as slicing, fancy indexing, and boolean indexing. Slicing involves selecting a range of elements from an array, while fancy indexing allows you to select elements using a list or array of indices. Boolean indexing involves selecting elements based on a condition or logical expression.

NumPy array indexing can be used for a wide range of tasks, such as filtering data, selecting specific elements from an array, and performing mathematical operations on subsets of an array. With its efficient array indexing capabilities, NumPy is an essential tool for many scientific and data analysis applications in Python.
To access elements or subsets of a NumPy array, you can use indexing. NumPy provides several ways to index arrays, including basic indexing, advanced indexing, and Boolean indexing.

# Basic Indexing:
Basic indexing involves accessing elements at specific indices using square brackets [].
The indices start from 0 for the first element.

***(01) index one-dimension Array***

**Example**

In [ ]:
import numpy as np
a = np.array([2,3,5,6,7,8])
print(a[0])


2


This code imports the NumPy library and creates a NumPy array called a with the elements [2, 3, 5, 6, 7, 8]. The print(a[0]) statement is used to access and print the first element of the array, which has an index of 0.

***index (negative)1-D Array***

In [ ]:
import numpy as np
a = np.array([2,3,5,6,7,8])
print(a[-4])


5


***(02) index Two-dimension Array***

This code builds a 2-dimensional NumPy array called a and imports the NumPy library. There are three rows and six columns in the array a.

In [ ]:
import numpy as np
a = np.array([[2,3,5,6,7,8],[9,11,12,13,14,15],[2,7,9,10,11,12]])
print(a[2,4])


11


he third row (index 2) and fifth column (index 4) of the array an are intersected by an element, which can be accessed and printed using the print(a[2, 4]) command.

**index (negative)2-D Array**

In this code, we have a 2-dimensional NumPy array called a with three rows and six columns

In [ ]:
import numpy as np
a = np.array([[2,3,5,6,7,8],[9,11,12,13,14,15],[2,7,9,10,11,12]])
print(a[-3,-4])

5


The print(a[-3, -4]) statement is used to access and print the element at the intersection of the third row from the end (index -3) and the fourth column from the end (index -4) of the array a.

**(03) index Three-dimension Array**

In this code, we have a 3-dimensional NumPy array called a. The array a has two blocks, each containing two rows and six columns

In [ ]:
import numpy as np
a = np.array([[[2,3,5,6,7,8],[9,11,12,13,14,15]],[[2,7,9,10,11,12],[13,14,15,16,17,18]]])
print(a[1,1,2])

15


The print(a[1, 1, 2]) statement is used to access and print the element at the intersection of the second block (index 1), second row (index 1), and third column (index 2) of the array a.

**index (negative)3-D Array**

In [ ]:
import numpy as np
a = np.array([[[2,3,5,6,7,8],[9,11,12,13,14,15]],[[2,7,9,10,11,12],[13,14,15,16,17,18]]])
print(a[-2,-1,2])

12


**(04) index Four-dimension Array**



In [ ]:
import numpy as np
a = np.array([[[[2,3,5,6,7,8]]]])
print(a[0,-1,0,2])

5


In this code, we have a 4-dimensional NumPy array called a. The array a contains a single element, which is a 1-dimensional array [2, 3, 5, 6, 7, 8]. The shape of a is (1, 1, 1, 6).

The print(a[0, -1, 0, 2]) statement is used to access and print the element at the intersection of the first dimension with index 0, the second dimension with index -1, the third dimension with index 0, and the fourth dimension with index 2 of the array a.

**Update the array by indexing**

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
# Accessing single element
print(arr[3])
# Update single element
arr[3]=12
print(arr)


4
[ 1  2  3 12  5]


# Boolean Indexing:
Boolean indexing involves using a boolean array of the same shape as the original array to select elements.
Elements corresponding to True values in the boolean array are selected.

In [ ]:
import numpy as np
arr = np.array ([1,2,3,4,5])
bool_arr= np.array([True , False ,True , False ,True ])
print(arr[bool_arr])

arr[bool_arr]=10
print(arr)

[1 3 5]
[10  2 10  4 10]


In [ ]:
import numpy as np
A = np.array ([[[34,25,16,78,4,9],[45,33,22,11,56,66]],[[90,55,53,23,12,23],[23,65,45,83,27,44]]])
print(A)
d=np.ndim(A)
print("Dimensional Array=",d)
print("Array shape=",np.shape(A))
#print("Reshape=",np.reshape(2,12))

print("size=", np.size(A))
print()
print("by index=",A[1])
print("Array 1 index 0=",A[1,0])
print("Array 1 by index 1=",A[1,1])
print()
print("by index=",A[0])
print("Array 0  index 0=",A[0,0])
print()
print("Array 0  index 1=",A[0,1])
print(A[0,1,2])
print(A[0,1,3])
print(A[0,1,0])
print(A[0,0,4])

print(A[1,1,2])
print(A[1,1,3])
print(A[1,1,0])
print(A[1,1,4])


[[[34 25 16 78  4  9]
  [45 33 22 11 56 66]]

 [[90 55 53 23 12 23]
  [23 65 45 83 27 44]]]
Dimensional Array= 3
Array shape= (2, 2, 6)
size= 24

by index= [[90 55 53 23 12 23]
 [23 65 45 83 27 44]]
Array 1 index 0= [90 55 53 23 12 23]
Array 1 by index 1= [23 65 45 83 27 44]

by index= [[34 25 16 78  4  9]
 [45 33 22 11 56 66]]
Array 0  index 0= [34 25 16 78  4  9]

Array 0  index 1= [45 33 22 11 56 66]
22
11
45
4
45
83
23
27


In [ ]:
A = np.array ([[[[34,25,16,78,4,9],[45,33,22,11,56,66]],[[90,55,53,23,12,23],[23,65,45,83,27,44]],[[5,4,3,22,8,67],[7,6,4,3,7,5]]]])
print(A)
print("Slicing")
print(A[0:4:2, 1:3:2])

[[[[34 25 16 78  4  9]
   [45 33 22 11 56 66]]

  [[90 55 53 23 12 23]
   [23 65 45 83 27 44]]

  [[ 5  4  3 22  8 67]
   [ 7  6  4  3  7  5]]]]
Slicing
[[[[90 55 53 23 12 23]
   [23 65 45 83 27 44]]]]
