<a href="https://colab.research.google.com/github/eisakhan04/Numpy-Course/blob/main/Topic_07_Hyperbolaic_Function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Topic 07: Hyperbolaic Function**
 1. sinh(x)
 2. cosh(x)
 3. tanh(x)
 4. arcsinh(x)
 5. arccosh(x)
 6. arctanh(x)

NumPy is a popular library in Python used for scientific computing, particularly in the fields of data analysis and machine learning. One of the many features of NumPy is its implementation of hyperbolic functions.

Hyperbolic functions are a set of six functions that are analogous to the trigonometric functions. Just as the sine, cosine, and tangent functions are used to describe the relationships between angles and sides of triangles, the hyperbolic functions are used to describe the relationships between the sides of a hyperbola.

The six hyperbolic functions that are available in NumPy are:

* numpy.sinh(x): Returns the hyperbolic sine of x.
* numpy.cosh(x): Returns the hyperbolic cosine of x.
* numpy.tanh(x): Returns the hyperbolic tangent of x.
* numpy.arcsinh(x): Returns the inverse hyperbolic sine of x.
* numpy.arccosh(x): Returns the inverse hyperbolic cosine of x.
* numpy.arctanh(x): Returns the inverse hyperbolic tangent of x.
These functions can be useful in a variety of applications, such as in statistics, physics, and engineering. For example, the hyperbolic functions are used to describe the shape of a catenary curve, which is the curve formed by a hanging chain or cable. They can also be used to model various physical phenomena, such as the behavior of electrical circuits and the motion of particles in a magnetic field.

In summary, NumPy provides a set of hyperbolic functions that can be used for a variety of applications in scientific computing. These functions are analogous to the trigonometric functions and can be used to describe relationships between the sides of a hyperbola.

# **Hyperbolic Function use in Formulas given this**
1. sinh(x) => sinh(x) = (e^x - e^(-x))/2
2. cosh(x) => cosh(x) = (e^x + e^(-x))/2
3. tanh(x) => tanh(x) = (e^x - e^-x)/(e^x + e^-x)
4. arctanh(x)=>arctanh(x) = 0.5 * ln((1+x)/(1-x))
5. arcsinh(x)=>arcsinh(x) = ln(x + sqrt(x^2 - 1))
6. arccosh(x)=>arccosh(x)=ln(x + sqrt(x^2 + 1))
in this formula arc means **inverse**


**Sinh(x) and arcSinh(x) Function**

This Python program uses the NumPy library to perform hyperbolic sine (sinh) and inverse hyperbolic sine (arcsinh) calculations on a given array. Here's the complete explanation of the program:

Import NumPy Library:
The program starts by importing the NumPy library and assigning it the alias "np." NumPy is a powerful library for numerical computations in Python, and it provides support for various mathematical operations on arrays.

In [ ]:
import numpy as np
a = np.array([2,3,4])
b = np.sinh(a)
print("Sinh Values")
print(b)
print()
c = np.arcsinh(a)
print(c)


**Complete Explanation:**

Calculate Hyperbolic Sine (sinh) Values:
The program then uses the NumPy function 'np.sinh()' to calculate the hyperbolic sine of each element in the array 'a'. The result is stored in a new array 'b'. The hyperbolic sine of a number 'x' is defined as (e^x - e^(-x)) / 2, where 'e' is Euler's number, approximately equal to 2.71828.


> Calculate Inverse Hyperbolic Sine (arcsinh) Values:
Next, the program uses the NumPy function 'np.arcsinh()' to calculate the inverse hyperbolic sine of each element in the array 'a'. The result is stored in a new array 'c'. The inverse hyperbolic sine of a number 'x' is defined as ln(x + sqrt(x^2 + 1)), where 'ln' is the natural logarithm and 'sqrt' is the square root.



# **sinh(x) and arcsinh(x) Function**

In [ ]:
import numpy as np
a = np.array([5,6,7,8,9])
sinh=np.sinh(a)
print(sinh)
inverse=np.arcsinh(a)
print(inverse)

[  74.20321058  201.71315737  548.31612327 1490.47882579 4051.54190208]
[2.31243834 2.49177985 2.64412076 2.77647228 2.89344399]


**Explanation:**

**Import NumPy Library:**
The program starts by importing the NumPy library and assigning it the alias "np." NumPy is a powerful library for numerical computations in Python, and it provides support for various mathematical operations on arrays.

Define the Input Array:
The program creates a NumPy array named 'a' with the elements [5, 6, 7, 8, 9]. This array will be used for the sinh and arcsinh calculations.

Calculate Hyperbolic Sine (sinh) Values:
The program uses the NumPy function 'np.sinh()' to calculate the hyperbolic sine of each element in the array 'a'. The result is stored in a new array 'sinh'. The hyperbolic sine of a number 'x' is defined as (e^x - e^(-x)) / 2, where 'e' is Euler's number, approximately equal to 2.71828.

Print the Sinh Values:
The program prints the array 'sinh', which contains the hyperbolic sine values of the elements in array 'a'.

Calculate Inverse Hyperbolic Sine (arcsinh) Values:
Next, the program uses the NumPy function 'np.arcsinh()' to calculate the inverse hyperbolic sine of each element in the array 'a'. The result is stored in a new array 'inverse'. The inverse hyperbolic sine of a number 'x' is defined as ln(x + sqrt(x^2 + 1)), where 'ln' is the natural logarithm and 'sqrt' is the square root.

Print the Arcsinh Values:
The program prints the array 'inverse', which contains the inverse hyperbolic sine values of the elements in array 'a'.



# **cosh(x) and arccosh(x) Function**

In [ ]:
a= np.array([2,3,1,4])
cosh=np.cosh(a)
print(cosh)
b=np.arccosh(a)
print(b)

[ 3.76219569 10.067662    1.54308063 27.30823284]
[1.3169579  1.76274717 0.         2.06343707]


**Explanation**:

**Import NumPy Library:**
The program starts by importing the NumPy library and assigning it the alias "np." NumPy is a powerful library for numerical computations in Python and provides support for various mathematical operations on arrays.

Define the Input Array:
The program creates a NumPy array named 'a' with the elements [2, 3, 1, 4]. This array will be used for the cosh and arccosh calculations.

Calculate Hyperbolic Cosine (cosh) Values:
The program uses the NumPy function 'np.cosh()' to calculate the hyperbolic cosine of each element in the array 'a'. The result is stored in a new array 'cosh'. The hyperbolic cosine of a number 'x' is defined as (e^x + e^(-x)) / 2, where 'e' is Euler's number, approximately equal to 2.71828.

Print the Cosh Values:
The program prints the array 'cosh', which contains the hyperbolic cosine values of the elements in array 'a'.

Calculate Inverse Hyperbolic Cosine (arccosh) Values:
Next, the program uses the NumPy function 'np.arccosh()' to calculate the inverse hyperbolic cosine of each element in the array 'a'. The result is stored in a new array 'b'. The inverse hyperbolic cosine of a number 'x' is defined as ln(x + sqrt(x^2 - 1)), where 'ln' is the natural logarithm and 'sqrt' is the square root.

Print the Arccosh Values:
The program prints the array 'b', which contains the inverse hyperbolic cosine values of the elements in array 'a'.

# **tanh(x) and arctanh(x) Function**

In [ ]:
q=np.array([1,2,3,4])
a=np.tanh(q)
print(a)


[0.76159416 0.96402758 0.99505475 0.9993293 ]


**Explanation:**

**Import NumPy Library:**
The program starts by importing the NumPy library and assigning it the alias "np." NumPy is a powerful library for numerical computations in Python and provides support for various mathematical operations on arrays.

Define the Input Array:
The program creates a NumPy array named 'q' with the elements [1, 2, 3, 4]. This array will be used for the hyperbolic tangent (tanh) calculation.

Calculate Hyperbolic Tangent (tanh) Values:
The program uses the NumPy function 'np.tanh()' to calculate the hyperbolic tangent of each element in the array 'q'. The result is stored in a new array 'a'. The hyperbolic tangent of a number 'x' is defined as (e^x - e^(-x)) / (e^x + e^(-x)), where 'e' is Euler's number, approximately equal to 2.71828.

Print the Tanh Values:
The program prints the array 'a', which contains the hyperbolic tangent values of the elements in array 'q'.

**Invers of tanh(x)**

In [ ]:
q=np.array([0.1,.2,.3,.4])
invrs=np.arctanh(q)
print(invrs)

[0.10033535 0.20273255 0.3095196  0.42364893]


**Explanation:**

**Import NumPy Library:**
The program starts by importing the NumPy library and assigning it the alias "np." NumPy is a powerful library for numerical computations in Python and provides support for various mathematical operations on arrays.

Define the Input Array:
The program creates a NumPy array named 'q' with the elements [0.1, 0.2, 0.3, 0.4]. This array will be used for the inverse hyperbolic tangent (arctanh) calculation.

Calculate Inverse Hyperbolic Tangent (arctanh) Values:
The program uses the NumPy function 'np.arctanh()' to calculate the inverse hyperbolic tangent of each element in the array 'q'. The result is stored in a new array 'invrs'. The inverse hyperbolic tangent of a number 'x' is defined as (1/2) * ln((1 + x) / (1 - x)), where 'ln' is the natural logarithm.

Print the Arctanh Values:
The program prints the array 'invrs', which contains the inverse hyperbolic tangent values of the elements in array 'q'.