<a href="https://colab.research.google.com/github/eisakhan04/Numpy-Course/blob/main/Topic_14_Copy_and_view_numpy_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Topic 14: Copy and view numpy function**

NumPy is a popular library in Python for numerical computing. It provides an efficient way to work with arrays and matrices. When working with NumPy arrays, it is important to understand the concepts of copying and viewing arrays.

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

**Numpy. Copy() Function:**

The copy() function in NumPy creates a deep copy of an array or a matrix. This means that a new object is created with its own memory, and any changes made to the new object will not affect the original array or matrix.





In [6]:
import numpy as np
a=np.array([2,3,4,5])
print("orignal array :",a)
print()
b=a.copy()
print("copy array :",b)

orignal array : [2 3 4 5]

copy array : [2 3 4 5]


In [8]:
# numpy two deminsional array
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
b=a.copy()
print("original array:",a)
print()
print("copy array:",b)


original array: [[1 2 3 4]
 [5 6 7 8]]

copy array: [[1 2 3 4]
 [5 6 7 8]]


**Example 04: Creating a copy of a slice of an array:**

In [2]:

import numpy as np

a = np.array([[1, 2], [3, 4]])
b = a[:,1].copy()
print("original array:",a)
print()
print("copy array:",b)

original array: [[1 2]
 [3 4]]

copy array: [2 4]


**Example 05: Creating a copy of an array with a different data type:**

In [11]:
import numpy as np
a = np.array([1, 2, 3])
b= a.astype(float).copy()
print("original array:",a)
print()
print("copy float array:",b)
print()
c = a.astype(complex).copy()
print("copy complex array:",c)

original array: [1 2 3]

copy float array: [1. 2. 3.]

copy complex array: [1.+0.j 2.+0.j 3.+0.j]


In [12]:
import numpy as np
a = np.array([2,3,4,5])
#list value is change copy()function is change
a[1] = 43
a[2]=32
print("original array",a)
print()
b = a.copy()
print("copy array",b)

original array [ 2 43 32  5]

copy array [ 2 43 32  5]


In [ ]:
import numpy as np
a = np.array([2,3,4,5])
b = a.copy()
#list value is change copy()function is not change
a[1] = 43
print("original array",a)
print()
print("copy array",b)



original array [ 2 43  4  5]

copy array [2 3 4 5]


In [ ]:
import numpy as np
a = np.array([2,3,4,5])
b = a.astype(float).copy()
print(b)

[2. 3. 4. 5.]


In [ ]:
import numpy as np
a = np.array([2,3,4,5])
print(a)
b = a.astype(complex).copy()
print(b)

[2 3 4 5]
[2.+0.j 3.+0.j 4.+0.j 5.+0.j]


**Numpy.view() Function**
1. The view() function in NumPy allows you to create a new array object that shares the same data as the original array, but with a different shape or data type. The new array object created by view() is a shallow copy, which means that the data is not copied, only the metadata is changed. Therefore, changes made to the new array object will also affect the original array.

2. The view() function can be useful for reshaping or casting arrays. For example, you can use view() to create a new array with the same data but a different shape, without having to copy the data. This can save memory and time.

3. It's important to note that the new array created by view() is not a completely independent copy of the original array. Any changes made to the new array will also affect the original array, and vice versa. So, if you need a completely independent copy of an array, you should use the copy() function instead.

In [ ]:
import numpy as np
a = np.array([2,3,4,5])
b = a.view()
a[1] = 43
print("original array",a)
print()
print("copy array",b)

original array [ 2 43  4  5]

copy array [ 2 43  4  5]


In [3]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
b = a.view()
b[0] = 31
print("original array:",a)
print()
print("view array:",b)

original array: [31  2  3  4  5]

view array: [31  2  3  4  5]


In [4]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
print(x.base)
print()
print(y.base)

None

[1 2 3 4 5]


**Explanation**

The "copy" method is then used to create a deep copy of "arr" and assign it to variable "x". A deep copy means that a completely new array is created with the same values as "arr", so any changes to "x" will not affect "arr".

The "view" method is also used to create a shallow copy of "arr" and assign it to variable "y". A shallow copy means that a new array is created with the same data pointer as "arr", so any changes to "y" will affect "arr".

Finally, the "base" attribute is accessed for both "x" and "y". If the array is a view, the "base" attribute returns the original array, otherwise it returns None.

The output of the code will show that "x.base" is None, indicating that "x" is a standalone array with no base array. "y.base" is "arr", indicating that "y" is a view of the "arr" array.