<a href="https://colab.research.google.com/github/eisakhan04/Numpy-Course/blob/main/Topic_11_NumPy_Searching_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Topic 11: NumPy Searching Arrays**

# Topic 11: NumPy Searching Arrays
NumPy provides a number of functions for searching arrays. Some of the most commonly used functions are:

1. where() : This function returns the indices of elements in an input array where the given condition is satisfied.
2. argmin() : This function returns the index of the minimum value in an array.
3. argmax() : This function returns the index of the maximum value in an array.
4. searchsorted() : This function returns the index where the specified value would be inserted to maintain the search     order.

**Numpy where() function**

In [ ]:
import numpy as np
a =np.array([[1,2,3,4,5,6]])
b= np.where(a==5)
print("this value index is=",b)

# Explanation
This program first imports the numpy library. Then, it creates a NumPy array a with the values 1, 2, 3, 4, 5, and 6. Next, it uses the where() function to find the indices of all the elements in a that are equal to 5. The where() function returns a tuple of two arrays, the first of which contains the indices of the elements that match the condition, and the second of which contains the values of the elements that match the condition. In this case, the first array will contain a single element, which is the index of the 5 in a. Finally, the program prints the value of the b tuple, which is the index of the 5 in a.



In [4]:
a =np.array([[1,2,5,4,5,6,5,6,7]])
b=np.where(a==5)
print(b)

(array([0, 0, 0, 1, 1, 1]), array([2, 5, 7, 0, 3, 7]))


In [ ]:
a =np.array([[1,2,5,4,5,6,5,6,7],[43,53,55,72,33,33,44,67,55]])
b=np.where(a==55)
print(b)

**Find Even Number by where() function**

In [5]:
a =np.array([[1,2,5,4,5,6,5,6,7],[43,53,55,72,33,33,44,67,55]])
b=np.where(a%2==0)
print(b)

(array([0, 0, 0, 0, 1, 1, 1, 1, 1]), array([2, 4, 5, 7, 0, 2, 3, 6, 7]))


# Explanation
This program first imports the numpy library. Then, it creates a NumPy array a with the values 1, 2, 5, 4, 5, 6, 5, 6, 7, 43, 53, 55, 72, 33, 33, 44, 67, 55. Next, it uses the where() function to find the indices of all the elements in a that are even numbers. The where() function returns a tuple of two arrays, the first of which contains the indices of the elements that match the condition, and the second of which contains the values of the elements that match the condition. In this case, the first array will contain the indices of all the even numbers in a, and the second array will contain the values of all the even numbers in a. Finally, the program prints the value of the b tuple, which is a tuple of two arrays containing the indices and values of all the even numbers in a.

In other words, this program finds the indices and values of all the even numbers in the NumPy array a and prints them out.

The output of the program will be a tuple of two arrays:

(array([0, 1, 3, 5, 7, 9]), array([1, 5, 7, 3, 6, 5]))
The first array contains the indices of the even numbers in a, and the second array contains the values of the even numbers in a.

**Find Odd Number by where() function**

In [6]:
a =np.array([[1,2,5,4,5,6,5,6,7],[43,53,55,72,33,33,44,67,55]])
b=np.where(a%2==1)
print(b)

(array([0, 0, 0, 0, 1, 1, 1]), array([0, 1, 3, 6, 1, 4, 5]))


# Explanation:
This program first imports the numpy library. Then, it creates a NumPy array a with the values 1, 2, 5, 4, 5, 6, 5, 6, 7, 43, 53, 55, 72, 33, 33, 44, 67, 55. Next, it uses the where() function to find the indices of all the elements in a that are odd numbers. The where() function returns a tuple of two arrays, the first of which contains the indices of the elements that match the condition, and the second of which contains the values of the elements that match the condition. In this case, the first array will contain the indices of all the odd numbers in a, and the second array will contain the values of all the odd numbers in a. Finally, the program prints the value of the b tuple, which is a tuple of two arrays containing the indices and values of all the odd numbers in a.

In other words, this program finds the indices and values of all the odd numbers in the NumPy array a and prints them out.

The output of the program will be a tuple of two arrays:

(array([0, 2, 4, 6, 8, 9, 10, 11, 12]), array([1, 3, 5, 7, 9, 5, 7, 9, 5]))
The first array contains the indices of the odd numbers in a, and the second array contains the values of the odd numbers in a.


**argmax() function argument maximum function in numpy**

In [10]:
import numpy as np
a = np.array([[1,3,4,5,6,4,9,4],[4,9,6,4,3,9,88,4]])
b = np.argmax(a)
print(b)

14


In [ ]:
a = np.array([[1,3,4,5,6,4,9,4],[4,9,6,4,3,9,88,4]])
b=np.argmax(a)
print(b)

# Explanation:
This program first imports the numpy library. Then, it creates a NumPy array a with the values 1, 3, 4, 5, 6, 4, 9, 4, 4, 9, 6, 4, 3, 9, 88, 4. Next, it uses the argmax() function to find the index of the maximum value in a. The argmax() function returns the index of the element with the maximum value in the array. In this case, the maximum value in a is 88, and its index is 14. Finally, the program prints the value of the b variable, which is the index of the maximum value in a.

The output of the program will be 14.

**argmin() function argument minimum function in numpy**

In [ ]:
a = np.array([[1,3,4,5,6,4,9,4],[4,9,6,4,3,9,88,4]])
b=np.argmin(a)
print(b)

# Explanation:
This program first imports the numpy library. Then, it creates a NumPy array a with the values 1, 3, 4, 5, 6, 4, 9, 4, 4, 9, 6, 4, 3, 9, 88, 4. Next, it uses the argmin() function to find the index of the minimum value in a. The argmin() function returns the index of the element with the minimum value in the array. In this case, the minimum value in a is 1, and its index is 0. Finally, the program prints the value of the b variable, which is the index of the minimum value in a.

The output of the program will be 0.

In [19]:
import numpy as np
a = np.array([[1,3,4,5,6,4,9,4],[4,9,6,4,3,9,88,4]])
b = np.argmin(a)
print(b)

0


**searchsorted() function**

In [ ]:
a = np.array([1,3,4,5,6,4,9,4])
value=9
b=np.searchsorted(a,value)
print(b)

# Explanation
This program first imports the numpy library. Then, it creates a NumPy array a with the values 1, 3, 4, 5, 6, 4, 9, 4. Next, it uses the searchsorted() function to find the index where the value 9 would be inserted to maintain the search order. The searchsorted() function returns the index of the first element in a that is greater than or equal to the value, or the length of a if no such element exists. In this case, the value 9 would be inserted at index 4 in a to maintain the search order, so the output of the program will be 4.

The output of the program will be 4.

In [18]:
import numpy as np

arr = np.array([8,6, 7, 9])

x = np.searchsorted(arr, 7)

print(x)

2


In [17]:
import numpy as np

arr = np.array([6, 7, 8, 9,10,5,12])
arr = np.array([6, 7, 8, 9,10,5,12])
x = np.searchsorted(arr, 5, side='right')

print(x)

0
