<a href="https://colab.research.google.com/github/onlyone11s/Numpy-Course/blob/main/Topic_2_Numpy_array_Creation_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Topic 02: Numpy Array Creation***
Numpy is a popular Python library used for scientific computing, particularly for working with arrays. Numpy arrays are similar to Python lists, but they offer more efficient and convenient ways to perform mathematical operations on large datasets.

# There are several ways to create a numpy array.
# 1.Creating an array from a list or tuple:
import numpy as np my_list = [1, 2, 3, 4, 5] my_array = np.array(my_list) Creating an array of random values:

# 2.Creating an array of zeros or ones:
zeros_array = np.zeros(5) # creates an array of five zeros ones_array = np.ones(3) # creates an array of three ones

# 3.Creating an array with a arange of values:
range_array = np.arange(0, 10, 2) # creates an array with values from 0 to 8 in increments of 2
# 4.Creating an array of random values:
random_array = np.random.rand(3, 4) # creates a 3x4 array of random values between 0 and 1

# 5.Creating an array of evenly spaced values:
linear_array = np.linspace(0, 1, 11) # creates an array of 11 evenly spaced values between 0 and 1

These are just a few examples of ways to create numpy arrays. Numpy also provides many functions to manipulate arrays, such as reshaping, slicing, and concatenating, among others.

# 1.Creating an array from a list or tuple:

***Example 01***

 ***function:***
 zeros,ones,arange,reshape,linspace

# **zeros function**

In [1]:
# 1D array
import numpy as np
a = np.zeros(4)
print(a)

[0. 0. 0. 0.]


In [9]:
# 2D array
import numpy as np
a = np.zeros((4,2))
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
import numpy as np

# Creating a 1D array of zeros
zeros_1d = np.zeros(5)
print("1D Array of Zeros:")
print(zeros_1d)

# Creating a 2D array of zeros
zeros_2d = np.zeros((3, 4))
print("2D Array of Zeros:")
print(zeros_2d)

# Creating a 3D array of zeros
zeros_3d = np.zeros((2, 3, 2))
print("3D Array of Zeros:")
print(zeros_3d)

# ***ones function***

In [10]:
import numpy as np
a = np.ones(3)
print(a)

[1. 1. 1.]


In [ ]:
import numpy as np
a = np.ones((3,5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


**Arange function**

In [ ]:
import numpy as np
a = np.arange(0,5)
print(a)

[0 1 2 3 4]


In [ ]:
import numpy as np
a = np.arange(1,10,4)
print(a)

[1 5 9]


**linspace function**

In [ ]:
import numpy as np
a = np.linspace(1,5)
print(a)

[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


In [15]:
import numpy as np
a = np.linspace(1,20,3)
print(a)

[ 1.  10.5 20. ]


In [12]:
import numpy as np
a = np.linspace(0, 1, 11)
print(a)


[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [ ]:
import numpy as np
a = np.arange(1,10)
print(a)
print("Reshape array")
b = a.reshape(3,3)
print(b)

[1 2 3 4 5 6 7 8 9]
Reshape array
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np
a = np.arange(1,17)
print(a)
print("Reshape array")
b = a.reshape(16,1)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
Reshape array
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]]


In [ ]:
import numpy as np
a = np.arange(1,16)
print(a)
print("Reshape array")
b = a.reshape(15,1)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Reshape array
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]]


# Creating an array of random values:

In [11]:
import numpy as np
a = np.random.rand(2, 4)
print(a)

[[0.52798627 0.3450131  0.88189535 0.21797318]
 [0.89549755 0.27145711 0.69203339 0.23985624]]


The code you provided creates a 2-dimensional NumPy array called "a" that has 3 rows and 4 columns. The values in the array are randomly generated using the "np.random.rand()" function, which creates an array of random numbers uniformly distributed between 0 and 1. The resulting array is then printed using the "print()" function.