<a href="https://colab.research.google.com/github/onlyone11s/Numpy-Course/blob/main/Topic_05_Numpy_array_Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Topic 05: Numpy array Slicing**  
NumPy Array slicing is a technique to extract a portion of a NumPy array. It is done by specifying a range of indices separated by a colon inside the square brackets used to access an array element.



#**The basic syntax for array slicing in NumPy is:**
new_array = old_array[start:end:step]

Here, start represents the starting index of the slice, end represents the ending index (exclusive) of the slice, and step represents the step size between each element in the slice.

Array slicing can be performed on one-dimensional, two-dimensional, or higher-dimensional arrays in NumPy. It is a very powerful and efficient way to manipulate and extract data from arrays, as it avoids the need for iterating through each element manually.

**start,end,step**

**positive index (0 to n-1) negative index (-1 to -n)**

**start with 1 indexes and end brfore 4 indexes**

**Negative Slicing**

**Example 1:**

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6,7])
print(a[1:4])
print(a[-1:-7:-2])

[2 3 4]
[7 5 3]


**start with 1 indexes and end brfore 8 indexes step 4**

**Example 2:**

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[1:8:4])

[2 6]


**start with -4 indexes and end brfore -1 indexes**

**Negative Slicing**

**Example 3:**

In [ ]:
a = np.array([1,2,3,4,5,6,7])
print(a[-4:-1])

[4 5 6]


**start with -4 indexes and end last indexe**

**Example 4:**

In [ ]:
a = np.array([1,2,3,4,5,6,7])
print(a[-4:])

[4 5 6 7]


**end before -4 indexe**

**Example 5:**

In [ ]:
a = np.array([1,2,3,4,5,6,7])
print(a[:-4])

[1 2 3]


**start with 4 indexes and end last indexe**

**Example 6:**

In [ ]:
a = np.array([1,2,3,4,5,6,7])
print(a[4:])

[5 6 7]


**start 1st indexe and end before 4 indexe**

**Example 7:**

In [ ]:
a = np.array([1,2,3,4,5,6,7])
print(a[:4])

[1 2 3 4]


**show the list indexe and start with 2 and end before 5 indexes**

**Example 8:**

In [ ]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,13]])
print(a[1,2:5])

[ 9 10 11]


**show the list indexe and start with 2 and end last indexes**

**Example 9:**

In [20]:
import numpy as np
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,13]])
print(a[1,2:])

[ 9 10 11 13]


**Example 10:**

In [4]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,13]])
print(a)
print(a[0:2,1:5])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 13]]
[[ 2  3  4  5]
 [ 8  9 10 11]]


**2D array Slicing**
**Example 11:**

In [5]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,13],[12,14, 15, 16, 17,18]])
print(a)
print(a[0:3,1:5])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 13]
 [12 14 15 16 17 18]]
[[ 2  3  4  5]
 [ 8  9 10 11]
 [14 15 16 17]]


**Example 12:**

**Example 13:**

In [ ]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,13],[12,14, 15, 16, 17,18]])
print(a[0:3,1:5])

[[ 2  3  4  5]
 [ 8  9 10 11]
 [14 15 16 17]]


**Example 14:**

In [ ]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,13],[12,14, 15, 16, 17,18]])
print(a[1:3,1:5])

[[ 8  9 10 11]
 [14 15 16 17]]


**First index means list wise**

**2nd index means in list element wise**
* **OR**
* **First index means Row and Second index means column**





**Example 15:**

In [6]:
import numpy as np
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,13],[12,14,15,16,17,18],[15,16,19,20,23,24]])
print(a)
print(a[1:3, 1:5])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 13]
 [12 14 15 16 17 18]
 [15 16 19 20 23 24]]
[[ 8  9 10 11]
 [14 15 16 17]]


**Example 16:**

In [ ]:
import numpy as np
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,13],[12,14,15,16,17,18],[15,16,19,20,23,24]])
print(a[0:3, 1:6])

[[ 2  3  4  5  6]
 [ 8  9 10 11 13]
 [14 15 16 17 18]]


#**Advance Numpy array Slicing**

#**explanation:**
**Importing NumPy:** The script begins by importing the NumPy library with the alias "np." NumPy is a powerful library in Python used for numerical computations, particularly for working with arrays and matrices.

**Defining Arrays:** Four lists, 'a', 'b', 'c', and 'd', are defined, each containing six integer elements. These lists represent different rows of a 2-dimensional array.

**Creating a 2D Array:** The script then combines lists 'a', 'b', and 'c' into a 2-dimensional NumPy array named 's.' This array has three rows (corresponding to 'a', 'b', and 'c') and six columns (since each row contains six elements).

**Printing the Array:** The script prints the entire 2D array 's' using the 'print' function.



In [ ]:
import numpy as np
a=[1,2,3,4,5,6]
b=[7,8,9,0,10,11]
c=[12,13,14,15,16,17]
d=[18,19,20,21,22,23]
s=np.array([a,b,c])
print(s)
print(np.size(s))
print(s[1:3,1:6:2])




**Slicing the Array:** The script uses slicing to extract a subset of the array 's.' Specifically, it takes rows 1 to 2 (exclusive of row 3) and columns 1 to 5 (exclusive of column 6) with a step of 2. The sliced array is then printed.