<a href="https://colab.research.google.com/github/eisakhan04/Numpy-Course/blob/main/Topic_16_numpy_Rounding_Decimal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Topic 14: Rounding Decimal:**

Rounding decimals means approximating a decimal number to the nearest whole number, or a specific number of decimal places, based on a set of rules. These rules can vary depending on the situation and the desired level of accuracy. Generally, rounding involves looking at the digit immediately to the right of the rounding point and determining whether to round up or down based on its value. For example, if rounding to the nearest whole number, any decimal less than 0.5 is rounded down, while any decimal greater than or equal to 0.5 is rounded up. Rounding can be useful in situations where exact values are not necessary or when dealing with large sets of data.

**There are primarily five ways of rounding off decimals in NumPy:**

1. truncation
2. fix
3. rounding
4. floor
5. ceil

**Type 1.The trunc() method:**

In NumPy is a mathematical function that returns the truncated value of an input array or scalar. It rounds the input values towards zero to the nearest integer or to a specified decimal place.

In [6]:
import numpy as np
a = np.array([-2.5, -1.7, 0.3, 1.5, 2.8])
print("Input array:",a)
print()

#b = np.trunc(a)
#print("output  array:",b)


Input array: [ 3. +0.j -1.7+0.j  0.3+0.j  1.5+0.j  2.8+0.j]



**Explanation:**

The given code creates a NumPy array named 'a' with five floating-point values: -2.5, -1.7, 0.3, 1.5, and 2.8. The 'print()' function is used to display this input array 'a' in the console.

Next, the 'np.trunc()' function from the NumPy library is applied to the input array 'a'. This function truncates the decimal part of each element in 'a' and returns an array of integers with the same shape as the input array. The truncated values are then stored in another array named 'b'.

Finally, the 'print()' function is used to display the resulting truncated array 'b' in the console.

In summary, the code truncates the decimal values of each element in an array of floating-point numbers using the NumPy library function 'np.trunc()'. It then stores the resulting truncated integer values in a new array 'b', and displays both the input array 'a' and the truncated output array 'b' in the console.

In [ ]:
import numpy as np
a = np.array([2.23,-3.34,5.467,3.678,-4.67])
b = np.trunc(a)
print(b)

[ 2. -3.  5.  3. -4.]


In [ ]:
import numpy as np
a = np.array([[4.55,6.66,1.34,4.23],[6.45,7.23,9.23,8.33]])
b = np.trunc(a)
print(b)

[[4. 6. 1. 4.]
 [6. 7. 9. 8.]]


**2. fix Decimal:**

numpy is a Python library that provides support for working with arrays and matrices of numerical data. The fix() function; is a part of this library and it is used to round off the given input values towards zero.

In [7]:
import numpy as np
a = np.array([2.23,-3.34,5.467,3.678,-4.67])
b = np.fix(a)
print(b)

[ 2. -3.  5.  3. -4.]


In [ ]:
import numpy as np
a = np.array([[4.23,5.34,6.43,7.43],[6.78,7.67,3.89,2.56],[5.23,5.67,7.34,8.90]])
b = np.fix(a)
print(b)

[[4. 5. 6. 7.]
 [6. 7. 3. 2.]
 [5. 5. 7. 8.]]


**Te 3. Numpy Arounding Methodyp**

The around() method in NumPy is a rounding function that is used to round off an array of numbers to a specified number of decimal places. It rounds the array elements to the nearest even number when the number is exactly halfway between two possible rounded values. The method takes two arguments: the input array and the number of decimal places to round to. If the second argument is omitted, the method rounds each element to the nearest integer. The around() method can be used on both one-dimensional and multi-dimensional arrays, and can be used to convert floating-point numbers to integers. It is a useful tool for data manipulation in scientific computing, data analysis, and machine learning applications.

In [8]:
import numpy as np
a = np.array([2.23,-3.34,5.467,3.678,-4.67])
b = np.around(a)
print(b)

[ 2. -3.  5.  4. -5.]


In [ ]:
import numpy as np
a = np.array([[3.45,5.56,2.33,7.89],[5.43,6.78,9.90,2.45]])
b = np.around(a)
print(b)

[[ 3.  6.  2.  8.]
 [ 5.  7. 10.  2.]]


In [ ]:
import numpy as np
a = np.array([2.235,-3.341,5.467,3.678,-4.6])
b = np.around(a,decimals=2)
print(b)

[ 2.24 -3.34  5.47  3.68 -4.6 ]


In [ ]:
import numpy as np
a = np.array([6.451,3.566,7.343,7.789])
b = np.around(a,decimals=2)
print(b)

[6.45 3.57 7.34 7.79]


**4. Floor Decimal**

lowest integer

**Type 4. Numpy floor() method**

The Numpy floor() function is a mathematical function that is used to round down the elements of an input array to the nearest integer or (round off decimals to the lower integer). The function returns a new array with the same shape as the input array.

In summary:

the Numpy floor() function is useful for mathematical operations that require rounding down of array elements to the nearest integer or multiple of a specified value.

In [ ]:
import numpy as np
a = np.array([2.235,-3.341,5.467,3.678,-4.6])
b = np.floor(a)
print(b)

[ 2. -4.  5.  3. -5.]


In [ ]:
import numpy as np
a = np.array([8.897,-8.367,9.4567,9.68,8.6])
b = np.floor(a)
print(b)

[ 8. -9.  9.  9.  8.]


**5.ceiling Decimal**

highest integer

**Type 5. Topic=Numpy ceil() method**

NumPy is a Python library used for numerical computing, and it includes a variety of mathematical functions. The ceil() function is one such function, and it is used to round up a given input to the nearest integer(round off decimal to the upper integer).

In [ ]:
import numpy as np
a = np.array([2.235,-3.341,5.467,3.678,-4.6])
b = np.ceil(a)
print(b)

[ 3. -3.  6.  4. -4.]


**Explanation:**

The provided code first creates a Python list named "a" with four floating-point values: -2.23, 0.12, -1.34, and 123.34.

Then, the code prints the contents of the "a" list to the console with the message "Input array:" using the Python "print()" function.

An empty line is printed to the console using the Python "print()" function with no argument.

Next, the code uses the NumPy function "np.ceil()" to round up the values in the "a" list to the nearest higher integer. The resulting array is stored in a new variable named "b".

Finally, the code prints the contents of the "b" array to the console with the message "Output array:" using the Python "print()" function.

In summary, this code demonstrates the use of NumPy's mathematical function "np.ceil()" to perform the ceiling operation on a list of values. The ceiling operation rounds a number up to the nearest integer.



In [ ]:
import numpy as np
a = np.array([2.67,3.6576,6.877,8.75])
b = np.ceil(a)
print(b)

[3. 4. 7. 9.]
