<a href="https://colab.research.google.com/github/eisakhan04/Numpy-Course/blob/main/Topic_08_Numpy_Broadcasting_Function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Topic 08: Numpy Broadcasting Function**

# **NumPy Broadcasting**
In Mathematical operations, we may need to consider the arrays of different shapes. NumPy can perform such operations where the array of different shapes are involved.

For example, if we consider the matrix multiplication operation, if the shape of the two matrices is the same then this operation will be easily performed. However, we may also need to operate if the shape is not similar.

# **Broadcasting Rules**
Broadcasting is possible if the following cases are satisfied.

1. The smaller dimension array can be appended with '1' in its shape.
2. Size of each output dimension is the maximum of the input sizes in the dimension.
3. An input can be used in the calculation if its size in a particular dimension matches the output size or its value is exactly 1.
4. If the input size is 1, then the first data entry is used for the calculation along the dimension.

**Broadcasting can be applied to the arrays if the following rules are satisfied.**

1. All the input arrays have the same shape.
2. Arrays have the same number of dimensions, and the length of each dimension is either a common length or 1.
3. Array with the fewer dimension can be appended with '1' in its shape.

**add() Function in numpy by Broadcasting with array**

In [ ]:
import numpy as np

a = np.array([1,2,3])
print("original array of a")
print(a)

b = np.array([[1,2,3],[4,5,6]])
print("original array of b")
print(b)

print("Adding two array")
c = np.add(a,b)
print(c)

**Explanation:**

**Import NumPy Library:**
The program starts by importing the NumPy library and assigning it the alias "np." NumPy is a powerful library for numerical computations in Python and provides support for various mathematical operations on arrays.

**Define the First Array 'a':**
The program creates a NumPy array named 'a' with the elements [1, 2, 3]. This array is a one-dimensional array.

**Print the Original Array 'a':**
The program then prints the original array 'a' using the 'print' function to display its contents.

**Define the Second Array 'b':**
The program creates a NumPy array named 'b' with the elements [[1, 2, 3], [4, 5, 6]]. This array is a two-dimensional array with two rows and three columns.

**Print the Original Array 'b':**
The program then prints the original array 'b' using the 'print' function to display its contents.

**Adding Two Arrays 'a' and 'b':**
The program uses the NumPy function 'np.add()' to add the elements of arrays 'a' and 'b' element-wise. Since 'a' is a one-dimensional array and 'b' is a two-dimensional array, broadcasting is performed to match the dimensions. The result is stored in a new array 'c'.

**Print the Resultant Array 'c':**
The program prints the array 'c', which contains the result of adding the arrays 'a' and 'b'. The output will be a two-dimensional array, where each element is the sum of the corresponding elements from 'a' and 'b'.

# **Addition**

In [ ]:
import numpy as np
a = np.array([[1,2,3],[6,7,8]])
print("original array of a")
print(a)
b = np.array([[1,2,3],[4,5,6]])
print("original array of b")
print(b)
print("Adding two array")
c = np.add(a,b)
print(c)

original array of a
[[1 2 3]
 [6 7 8]]
original array of b
[[1 2 3]
 [4 5 6]]
Adding two array
[[ 2  4  6]
 [10 12 14]]


# **Multiplication**
**multiply() Function in numpy by Broadcasting with array**

In [ ]:
import numpy as np
a = np.array([[1,2,3],[6,7,8]])
print("original array of a")
print(a)
b = np.array([[1,2,3],[4,5,6]])
print("original array of b")
print(b)
print("multiply two array")
c = np.multiply(a,b)
print(c)

# **Explanation:**

**Import NumPy Library:**
The program starts by importing the NumPy library and assigning it the alias "np." NumPy is a powerful library for numerical computations in Python and provides support for various mathematical operations on arrays.

**Define the First Array 'a':**
The program creates a NumPy two-dimensional array named 'a' with the elements [[1, 2, 3], [6, 7, 8]].

**Print the Original Array 'a':**
The program then prints the original array 'a' using the 'print' function to display its contents.

**Define the Second Array 'b':**
The program creates another NumPy two-dimensional array named 'b' with the elements [[1, 2, 3], [4, 5, 6]].

**Print the Original Array 'b':**
The program then prints the original array 'b' using the 'print' function to display its contents.

**Multiply Two Arrays 'a' and 'b' Element-wise:**
The program uses the NumPy function 'np.multiply()' to perform element-wise multiplication of the two arrays 'a' and 'b'. Element-wise multiplication means that each element of 'a' will be multiplied with the corresponding element of 'b'. The result is stored in a new array 'c'.

**Print the Resultant Array 'c':**
The program prints the array 'c', which contains the result of element-wise multiplication of arrays 'a' and 'b'. The output will be a two-dimensional array with each element being the product of the corresponding elements from 'a' and 'b'.

# **Subtract**
**subtract() Function in numpy by Broadcasting with array**

In [ ]:
import numpy as np

a = np.array([[1,2,3],[6,7,8]])
print("original array of a")
print(a)
b = np.array([[4,6,8],[4,5,6]])
print("original array of b")
print(b)
print("Subtraction two array")
c = np.subtract(a,b)
print(c)

# **Explanation:**

**Import NumPy Library:**
The program starts by importing the NumPy library and assigning it the alias "np." NumPy is a powerful library for numerical computations in Python and provides support for various mathematical operations on arrays.

**Define the First Array 'a':**
The program creates a NumPy two-dimensional array named 'a' with the elements [[1, 2, 3], [6, 7, 8]].

**Print the Original Array 'a':**
The program then prints the original array 'a' using the 'print' function to display its contents.

**Define the Second Array 'b':**
The program creates another NumPy two-dimensional array named 'b' with the elements [[4, 6, 8], [4, 5, 6]].

**Print the Original Array 'b':**
The program then prints the original array 'b' using the 'print' function to display its contents.

**Subtract Two Arrays 'a' and 'b' Element-wise:**
The program uses the NumPy function 'np.subtract()' to perform element-wise subtraction of the two arrays 'a' and 'b'. Element-wise subtraction means that each element of 'a' will be subtracted by the corresponding element of 'b'. The result is stored in a new array 'c'.

**Print the Resultant Array 'c':**
The program prints the array 'c', which contains the result of element-wise subtraction of arrays 'a' and 'b'. The output will be a two-dimensional array with each element being the difference of the corresponding elements from 'a' and 'b'.

**Divide() function**

In [ ]:
import numpy as np

a = np.array([[1,2,3],[6,7,8]])
print("original array of a")
print(a)
b = np.array([[4,6,8],[4,5,6]])
print("original array of b")
print(b)
print("Subtraction two array")
c = np.divide(a,b)
print(c)

# **Explanation:**

**Import NumPy Library:**
The program starts by importing the NumPy library and assigning it the alias "np." NumPy is a powerful library for numerical computations in Python and provides support for various mathematical operations on arrays.

**Define the First Array 'a':**
The program creates a NumPy two-dimensional array named 'a' with the elements [[1, 2, 3], [6, 7, 8]].

**Print the Original Array 'a':**
The program then prints the original array 'a' using the 'print' function to display its contents.

**Define the Second Array 'b':**
The program creates another NumPy two-dimensional array named 'b' with the elements [[4, 6, 8], [4, 5, 6]].

**Print the Original Array 'b':**
The program then prints the original array 'b' using the 'print' function to display its contents.

**Divide Two Arrays 'a' and 'b' Element-wise:**
The program uses the NumPy function 'np.divide()' to perform element-wise division of the two arrays 'a' and 'b'. Element-wise division means that each element of 'a' will be divided by the corresponding element of 'b'. The result is stored in a new array 'c'.

**Print the Resultant Array 'c':**
The program prints the array 'c', which contains the result of element-wise division of arrays 'a' and 'b'. The output will be a two-dimensional array with each element being the quotient of the corresponding elements from 'a' and 'b'.

# **Maximum**
**maximum() Function in numpy by Broadcasting with array**

In [ ]:
import numpy as np
a = np.array([[1,2,3],[6,7,8]])
print("original array of a")
print(a)
b = np.array([[1,2,3],[4,5,9]])
print("original array of b")
print(b)
print("Maximum two array")
c = np.maximum(a,b)
print(c)

# **Explanation:**

**Import NumPy Library:**
The program starts by importing the NumPy library and assigning it the alias "np." NumPy is a powerful library for numerical computations in Python and provides support for various mathematical operations on arrays.

**Define the First Array 'a':**
The program creates a NumPy two-dimensional array named 'a' with the elements [[1, 2, 3], [6, 7, 8]].

**Print the Original Array 'a':**
The program then prints the original array 'a' using the 'print' function to display its contents.

**Define the Second Array 'b':**
The program creates another NumPy two-dimensional array named 'b' with the elements [[1, 2, 3], [4, 5, 9]].

**Print the Original Array 'b':**
The program then prints the original array 'b' using the 'print' function to display its contents.

**Find the Element-Wise Maximum of Two Arrays 'a' and 'b':**
The program uses the NumPy function 'np.maximum()' to find the element-wise maximum of the two arrays 'a' and 'b'. Element-wise maximum means that for each corresponding element in 'a' and 'b', the greater of the two elements will be taken. The result is stored in a new array 'c'.

**Print the Resultant Array 'c':**
The program prints the array 'c', which contains the element-wise maximum of the arrays 'a' and 'b'. The output will be a two-dimensional array with each element being the maximum of the corresponding elements from 'a' and 'b'.

# **Minimum**
**minimum() Function in numpy by Broadcasting with array**

In [ ]:
import numpy as np
a = np.array([[1,4,5],[6,7,8]])
print("original array of a")
print(a)
b = np.array([[1,2,6],[4,5,9]])
print("original array of b")
print(b)
print("Minimum two array")
c = np.minimum(a,b)
print(c)

original array of a
[[1 4 5]
 [6 7 8]]
original array of b
[[1 2 6]
 [4 5 9]]
Minimum two array
[[1 2 5]
 [4 5 8]]


# **Explanation:**

**Import NumPy Library:**
The program starts by importing the NumPy library and assigning it the alias "np." NumPy is a powerful library for numerical computations in Python and provides support for various mathematical operations on arrays.

**Define the First Array 'a':**
The program creates a NumPy two-dimensional array named 'a' with the elements [[1, 4, 5], [6, 7, 8]].

**Print the Original Array 'a':**
The program then prints the original array 'a' using the 'print' function to display its contents.

**Define the Second Array 'b':**
The program creates another NumPy two-dimensional array named 'b' with the elements [[1, 2, 6], [4, 5, 9]].

**Print the Original Array 'b':**
The program then prints the original array 'b' using the 'print' function to display its contents.

**Find the Element-Wise Minimum of Two Arrays 'a' and 'b':**
The program uses the NumPy function 'np.minimum()' to find the element-wise minimum of the two arrays 'a' and 'b'. Element-wise minimum means that for each corresponding element in 'a' and 'b', the smaller of the two elements will be taken. The result is stored in a new array 'c'.

**Print the Resultant Array 'c':**
The program prints the array 'c', which contains the element-wise minimum of the arrays 'a' and 'b'. The output will be a two-dimensional array with each element being the minimum of the corresponding elements from 'a' and 'b'.